### ISSUE TITLE
Chunk creation/loading suddenly stops

### ISSUE THREAD

**Issue by Vodrek7** [TerraForged/TerraForged#103]
**Description**
After i create a new world (on my friends pc the same happens) and the world is leoaded and we play inside it it suddenly stops loading new chunks. It gets very partially solved by reloading the save but it happens again too quickly so the game is rendered unplayable in chunks too far from the original spawn point.
Note that we play terraforged (latest version) on 1.15.2 with forge (latest) and other mods installed as well (they have nothing to do with world generation other than adding some occasional houses for example) (also no biome mods if that would play any role).

**How to reproduce**
- See below attached image for mods list

Step by step guide:
1) install forge latest
2) install terraforged latest
3) create new world with terraforged default (or even changed) values
4) fly over in creative mode until you reach a distance of 60 to 150 chunks from spawn point maybe? and there it stops generating new/loading them im not sure

my setup:
i5-6500 3.2 GHz
16 GB ram
Rx 590 Fatboy 8 GB GPU

**Additional information**
Mods currently used:
![Untitled-1](https://user-images.githubusercontent.com/62768304/77793314-83eab080-7072-11ea-8878-f82d8c5ba09e.jpg)

Link to sample video of the problem:
https://drive.google.com/open?id=1CPhAQLrRJbgYDGK59AZRNzbVBvH1oQ7z

**Comment by dags-** [comment]
It looks to be a clientside issue with chunk loading as opposed to a server-side issue with chunk generation.

The flickering chunks seen in the video show that the world has generated beyond the line of loading chunks, but for whatever reason your client is loading them. Perhaps you could try reducing your render distance, or increasing the ram allowance for your profile

**Comment by Vodrek7** [comment]
Hmm I will try these thanks, but keep in mind that it's also happening on a server me and my friend have built and are playing on and it happens to the same chunks for both of us at the same time
