### ISSUE TITLE
Leaf Decay

### ISSUE THREAD

**Issue by sasdef** [TerraForged/TerraForged#104]
Hey there,

I've noticed that the majority of large spruce I plant and chop down does not allow the leaves to decay. Sometimes the leaves disappear, but most of the time they don't. I've had some floating around for hours and other trees work so far, even with mods like fast decay.

Maybe your patterns for new trees simply have the non-decay leaf block in there? Hopefully you can fix it. It's nothing major but it makes survival a bit inconvenient.

- - -

Thank you for this mod, it is truly amazing! I love building medieval in survival but the default terrain just doesn't cut it and a lot of time is wasted terraforming, which isn't that viable. This has changed my Minecraft experience like nothing else in the past years! Good luck with further development. ^^

**Comment by sasdef** [comment]
Also this happens with no mods installed. Fresh new forge, fresh new world, hope this helps.

**Comment by dags-** [comment]
Thanks I'll look into it. Some of the trees were saved with persistent leaves by mistake

**Comment by dags-** [comment]
Fixed as of 0.0.11
