### ISSUE TITLE
Natural Snow Generator Creates Pseudo-Snow Grass Blocks

### ISSUE THREAD

**Issue by yurisuika** [TerraForged/TerraForged#105]
Perhaps this is intentional, but if it is I guess I am just not a fan of how it looks. When anything but a snow layer is placed on these blocks, they revert to grass blocks. If a snow layer is placed, it will remain as so, but will revert to grass after the snow layer has been broken.

I assume what is happening is that the generator removes the snow layers that it would otherwise place, but doesn't check if it is a grass block below and thus does not set it to the non-snowy state.

**How to reproduce**
- Enable Natural Snow Decorator

**Additional information**
Version 0.0.10
Forge 31.1.0
![2020-03-27_17 54 39](https://user-images.githubusercontent.com/7410303/77810883-1891e600-7054-11ea-8f5e-5074ebea69a8.png)

**Comment by Quizer9O8** [comment]
I can confirm this bug as well. It only seems to happen in snowy biomes AFAIK.

**Comment by dags-** [comment]
Thanks, this should be fixed as of 0.0.11
