### ISSUE TITLE
shader support?

### ISSUE THREAD

**Issue by tomorrowwwww** [TerraForged/TerraForged#106]
hey im new to this sorta stuff and im wondering if there is a way to use this with shaders the question might seem dumb but i am too. if there is no current support for shaders/optifine will there be in the soon future?
thanks,

**Comment by dags-** [comment]
Hi, not a problem!

TerraForged relies on Forge modloader. Optifine doesn't work with Forge at the moment. The Optifine developers are the only ones that can add the support/compatibility. When they do, it should work fine alongside TerraForged.

**Comment by Furigold** [comment]
You can try OptiForge
