### ISSUE TITLE
World gen bug

### ISSUE THREAD

**Issue by HolyRadiantPotato** [TerraForged/TerraForged#107]
**Description**
 A few chunks didn't generate correctly and appear as truncated. Not a case of vanilla generation reverting as the ground is laminated (strata).

**How to reproduce**
 generate a map on a forge server (last stable version) + terragen mod only 0.0.10

**Additional information**
![2020-03-29_18 05 22](https://user-images.githubusercontent.com/62420939/77854293-bff45180-71e9-11ea-87bf-62911d76a618.png)

**Comment by dags-** [comment]
Hi, please could you confirm which version you are using and provide the level.dat + coords for testing?

(might have to zip the level.dat to allow uploading here)

**Comment by HolyRadiantPotato** [comment]
tf 0.0.10
forge 31.1.0

[level.zip](https://github.com/TerraForged/TerraForged/files/4402150/level.zip)

**Comment by dags-** [comment]
Cool thanks. Seems to be some weird interaction between rivers and the custom terrain heights you're using - duplicating the world with scales set back to 1 works as normal

**Comment by dags-** [comment]
Cracked it!

There was a weird bug in the river carver that would lower the terrain dispraportionately at a handleful of points on the heightmap, creating a steep 'well'. Seems to have been exaggerrated by the custom settings but could probably also occur on defaults.

![2020-03-31](https://user-images.githubusercontent.com/4276064/78025633-44fa7a80-7352-11ea-9cc0-d2e0a7ebc0a4.png)
_Note the downward pointing spike_

Shapes like this in the terrain attract the focus of the erosion filter which then propgates the hole outwards until the entire region is flattened.

**Comment by HolyRadiantPotato** [comment]
Thanks,
I tried to delete the chunk and regen it with the 0.0.11 version, but it generated differently with no river, so I can't check if it does work.

**Comment by dags-** [comment]
Works when I recreate the world from scratch:

![2020-03-31_14 29 45](https://user-images.githubusercontent.com/4276064/78031950-27caa980-735c-11ea-8384-caf5696721be.png)

**Comment by HolyRadiantPotato** [comment]
That must be on my end then
