### ISSUE TITLE
Custom default settings are not applied to world creation

### ISSUE THREAD

**Issue by knoxx093** [TerraForged/TerraForged#108]
When terraforged-generator.json has been created with new default settings, these settings are displayed in the the 'customize' menu, but are not applied on world generation unless you enter the 'customize' menu and click 'Done'

**How to reproduce**
- Create New World
- Adjust settings in 'customize' menu for TerraForged world type.
- Click 'Set Defaults' 
- Reload game (or you might be able to just back out of the world creation screen)
- Create New World, set world type to TerraForged
- Click 'Create New World' again to generate world. Custom settings will not have been applied.

**Comment by dags-** [comment]
Thanks, this should be fixed as of 0.0.11
