### ISSUE TITLE
TerraTest Worldtype

### ISSUE THREAD

**Issue by NillerMedDild** [TerraForged/TerraForged#109]
Disclaimer: This feature request makes the assumption that the TerraTest worldtype is a development world - Please correct me if that is not the case :)
**Is your feature request related to a problem? Please describe.**
I've heard that some users pick TerraTest as worldtype when they make a new survival world, thinking it's TerraForged worldgen - I would like to disable the TerraTest option to prevent that.

**Describe the solution you'd like**
A config option to disable the ability to choose TerraTest worldtype

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by dags-** [comment]
Thanks, hidden in 0.0.11 unless launched with the `-Ddev` flag
