### ISSUE TITLE
just stumbled upon this, what is it?

### ISSUE THREAD

**Issue by gravestristen** [TerraForged/TerraForged#11]
i just stumbled upon this after finding your profile from the matmos site, what is this project?

**Comment by dags-** [comment]
Hi, this is a terrain generator that I'm working on. The mod part of it isn't public yet

**Comment by gravestristen** [comment]
it looks amazing, what version are you developing for?

**Comment by dags-** [comment]
I'm targetting forge 1.15.2 currently

**Comment by gravestristen** [comment]
very nice, i cant wait to try it when the beta comes out.

**Comment by dags-** [comment]
Thanks for your interest. Closing this as the first public version is now available on curseforge:
https://www.curseforge.com/minecraft/mc-mods/terraforged
