### ISSUE TITLE
Flat Bedrock

### ISSUE THREAD

**Issue by TheUntamed** [TerraForged/TerraForged#112]
I included _Better Bedrock Generator_ mod to flatten the bedrock but TerraForge World generation is overwriting it. With other world generation it works.

Overall it would be nice if TerraForge would add the feature to flatten the bedrock if wanted so no other mod is required to do that. This issue is also a feature request.

**Comment by dags-** [comment]
It wouldn't be hard but what's the benefit of this?
I do the same as vanilla at the moment - changing it would affect or spawning, albeit to a small degree

**Comment by TheUntamed** [comment]
A lot of people like flat bedrock.

**Comment by MisterDaen** [comment]
What TheUntamed is mentioning feels a bit like a bug, in terms of interaction with certain mods.  ImmersivePortals, for example, allows dimension stacking (nether under overworld) and is supposed to replace bedrock with obsidian so it can be mined,

TerraForged overwrites this behavior, making the dimension stacking largely pointless without additional mods (none of which seem to be updated for 1.15).

**Comment by dags-** [comment]
Thanks, that's a bit more of a reasonable use-case. I can probably add an option to let the user define a custom material

**Comment by MisterDaen** [comment]
That would be extremely helpful, yes, much appreciated!

**Comment by dags-** [comment]
Added to 0.0.14:

You can define the material, minimum height of the layer and the random variance.

If you want it to be flat you set 'variance' to 0 and set the 'depth' slider to however thick you want it to be.
