### ISSUE TITLE
Vanilla water/lava pools very frequent in 0.0.11

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#114]
Water and lava spawns are very excessive both above and below ground (and it might be nice to separate lava from water with the toggle so people who don't like lava pools above ground won't get them)
![2020-04-03_01 59 54](https://user-images.githubusercontent.com/33978024/78307669-1bf30900-754f-11ea-92fe-ad30acfedb19.png)

**Comment by dags-** [comment]
Yep, looks terrible but that's vanilla. The option's simply there to appease the people moaning about there not being any pools

**Comment by Monsterfisch** [comment]
would probably look alright if they are 5 times rarer than in the pic just so water isnt as extreme to come by

maybe even add groundwater by having waterlogged stone stairs and slabs underground around a certain height based on the biome (plains/swamps would be higher and mountains de
eper down
