### ISSUE TITLE
Improved feature placements

### ISSUE THREAD

**Issue by dags-** [TerraForged/TerraForged#116]
Improve feature placements to use systems like poisson disk sampling for more natural spread of objects/trees.

Allow for variable density and perhaps for density to reduce towards biome edges

**Comment by demonJ5** [comment]
Tapering trees towards the ends of biomes would do wonders for the realism and biome transitions.

**Comment by Quizer9O8** [comment]
Some kind of soil quality system would make exlopring a certain part in the world interesting as well. Trees can vary in size/thickness depending on the quality of the soil.

**Comment by dags-** [comment]
Soil quality is a property that is approximated throught the use of biomes. I don't think anything finer-grained would add that much value or be particularly noticeable
