### ISSUE TITLE
Structure loading system for TerraForged worlds

### ISSUE THREAD

**Issue by vico93** [TerraForged/TerraForged#120]
_Sorry to bother you again (already bothered on CF commends questioning common datapack loading, anyway...)_

Back in 1.12.2 i used [Pillar](https://www.curseforge.com/minecraft/mc-mods/pillar) ([Github](https://github.com/Vazkii/Pillar)) to generate random structures for my worlds. It differs a lot from the older AtomycStriker's Ruins because it uses the [vanilla mcstructure format](https://minecraft.gamepedia.com/Structure_Block) to store ruins, so far more easy and more vanilla-esque to create structures to load later. Plus it have [some interesting functionalities](https://docs.google.com/document/d/13wnL56VXB76Yth3lY__hP_8WAu5eYNWls0q4N-3VpVo/edit) (like using [structure blocks's DATA mode](https://minecraft.gamepedia.com/Structure_Block#Data) to load commands which are executed once when the structure loads) and other particular things

Well, for 1.15.2 Vazkii said he wont update the mod anymore due to massive changes in worldgen, so after you added the common datapack functionality i tried to get the chance to ask if you could add this functionality for TerraForged. Maybe loading the structures (separated by biome name folders) via datapacks (utilizing the common datapacks feature at fullest) or config, i don't know.

**Comment by dags-** [comment]
Yep this is planned

**Comment by SunScript0** [comment]
Bump to say this would be amazing. I was looking for some mod which could do this and nothing really works as well as i would like to. Personally i'd love this feature: just plop a structure nbt file in a folder, along with some config file and have it generate. Do you think this will be ready any time soon?

**Comment by SunScript0** [comment]
Hey dags, very cool that you added this! Is there anywhere I can learn how to use this feature?

**Comment by dagsy** [comment]
There's a 'datapacks' folder in `config/terraforged/` where you can add datapacks that replace the structures (it's a vanilla system so I'd assume there'll be some documentation if you google it)
