### ISSUE TITLE
Canyons

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#121]
**Is your feature request related to a problem?**

The lack of generation of biomes that are dependent on altitude, usually those that sometimes require high altitudes to spawn. Examples of these would be deserts and xeric forests (from BOP examples include Xeric Shrubland, Overgrown Cliffs, etc). This is because, as far as I know, world generation for plateaus averages at an altitude of y=128.

**Describe the solution you'd like**

An additional "Canyon" terrain type could be implemented, similar to mountains, dales, or plateaus.

Geographically, it would be similar to plateaus, albeit with more height variation in steps. It would also have an average altitude of whatever the user chooses as sea-level. I don't know if it is possible or not, but it might also be nice to have this region type be more likely to spawn inland, though their would be a small chance for it to also spawn near the ocean as well.

**Describe alternatives you've considered**

See "More climate controls to allow biasing of certain conditions [#87](https://github.com/TerraForged/TerraForged/issues/87)"

**Comment by Winddbourne** [comment]
This is definitely a good idea. :)

**Comment by demonJ5** [comment]
Deja vu

**Comment by Quizer9O8** [comment]
I have been in this place before...
