### ISSUE TITLE
Sub-Region Types

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#122]
**Is your feature request related to a problem? Please describe.**

Right now every "Region Type" stands for itself which is nice but there's no variation type inside the region itself. Normally in Minecraft sub-biomes come in play to give the dominating biome an alternate terrain variation. Examples of these would be Forest Hills inside of a Forest Biome, Flower Forest and etc.

**Describe the solution you'd like**

Geographically, it would have some characteristics from the parent terrain type which allows to create different type of terrain that would only be exlusive to that parent terrain type. For example dunes can only spawn inside of an desert terrain type.-- though can also spawn near the ocean as well.

**Describe alternatives you've considered**

None at the moment.

**Additional context**

None at the moment.

**Comment by dags-** [comment]
Not entirely true as there is a pool of terrain types from which blended variations are derived, leading to variation within a terrain region. Further dividing terrain regions, however, will not be a thing.

Biome specific terrain variation (ie desert dunes) can already be handled by the biome's surface builder.
