### ISSUE TITLE
[Feature Request] Ability to set this as the Default Generation type

### ISSUE THREAD

**Issue by Winddbourne** [TerraForged/TerraForged#123]
**Is your feature request related to a problem? Please describe.**

When players start my mod pack I can't seem to set things so that TerraForged is the default world type. A player actually has to go into advanced settings and choose this generation type every time they start a new world.  Otherwise they get the standard vanilla setup.

**Describe the solution you'd like**

I would like to have a configuration setting that would let me tell your mod to load up automatically unless the players go into the advanced settings and opt out of the experience I am crafting for them as a mod pack maker. 

It also would be nice to have the option to lock those settings if my pack really relies heavily on creating a world that has a certain feel to it. 

Finally it would be nice if you moved the JSON holding the default generation settings either into this configuration file, or at least put it in the TerraForged folder within the Cofig folder so that it is easier for me, as a pack maker, to quickly upload any/all settings I changed when I export my pack. 

**Describe alternatives you've considered**

The only alternative I see is to give my players a set of instructions they have to go through every time they start a game in my pack . . . you need to go into more world options and change your world type to "Terraforged" in order to get the best game experience, but please don't change any of the custom settings if you want to see the world as it is intended to generate. 

Doing that works, but it's klunky and it asks players to do extra steps when they should be able to just start a new world without thinking about it and be amazed when they get better generation, extra biomes, or whatever else I've done the work to give them.

**Comment by dags-** [comment]
As my response to #61 this would be better suited to a third party utility mod who could handle setting any world-type as the default.

I won't be adding such functionality into TF itself as there's too much scope for conflicting with other mods that might choose to do the same.

**Comment by CreativeRealms** [comment]
It shouldn't be enabled by default. There should just be a toggle-able option in the text configs as a utility for modpack devs who know what they are doing. I don't think that would create any inherent conflicts as it would not try to force a Terraforged world unless you set it to do so.

**Comment by dags-** [comment]
Again, this is something that a utility mod can handle
