### ISSUE TITLE
[Request] User control over strata blocks

### ISSUE THREAD

**Issue by lamoyrl90** [TerraForged/TerraForged#125]
First off: great mod, I love the feel of the terrain, both above ground and underground.

One thing I wish it had is control over what blocks can be strata layers. I haven't checked the code out itself, so I don't know exactly how it's all calculated, but it would be nice to at least define what blocks could be used as strata, and to be able to exclude others (I hate the new raw diorite texture). An extra layer of niceness would be having some control over what y-level each stratum material could be generated at, though this is just a secondary thought. Again, I don't know the underlying code so I don't know how difficult implementation of y-level control would be.

Afterthought question: does gravel still generate in pockets underground? I haven't seen it yet.

**Comment by Larky2k** [comment]
you can turn it off already

**Comment by dags-** [comment]
You can add/remove strata blocks via the block tags:
https://github.com/TerraForged/TerraForged/tree/master/TerraForgedMod/src/main/resources/data/forge/tags/blocks
