### ISSUE TITLE
TerraForged [0.0.10] Zombie Villagers Missing

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#126]
**Description**
Zombie Villagers are missing from a Zombified Village.

**How to reproduce**
- Create a new TerraForged World
- Locate the nearest village or fly to the cords down below

**Additional information**
This might be carried over to TF 0.0.11
Seed: -909685010 
Cords: X: 993 Z: 150
![afbeelding](https://user-images.githubusercontent.com/19509275/78397785-24505000-75f2-11ea-9463-63e665308678.png)

**Comment by dags-** [comment]
They're there in 0.0.11. Can't think of anything that'd have affected this in 0.0.10

![2020-04-03_21 17 46](https://user-images.githubusercontent.com/4276064/78401469-b6efef80-75f0-11ea-8a08-369b291ca135.png)
