### ISSUE TITLE
Player will sometimes spawn underground/inside stone.

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#127]
See title

**Comment by dags-** [comment]
I've never once had this happen. Custom settings?

**Comment by CreativeRealms** [comment]
Had to convert it to a .txt to upload it to github. It seems to happen when temperature/moisture sliders are changed. Besides that I don't know if it can occur in other cases.
[terraforged-generator.txt](https://github.com/TerraForged/TerraForged/files/4430895/terraforged-generator.txt)

**Comment by Ookreson** [comment]
Happens mostly when the height has been changed to something like 100+ or so on my end, I don't touch the temp/moisture slider. Just trying to get that TFC feel.

I'll get a text up later today

**Comment by dags-** [comment]
Thankfully forge makes this pretty easy to override

**Comment by dags-** [comment]
Should be much improved in 0.0.13
