### ISSUE TITLE
Ability to Adjust Distances Between Lakes

### ISSUE THREAD

**Issue by demonJ5** [TerraForged/TerraForged#129]
**Is your feature request related to a problem? Please describe.**
While the vanilla water features option is a tremendous boon for survival gameplay, it does come at a cost. The frequency at which these lakes spawn can sometimes detract from the beauty and realism that Terraforged's worldgen provides; see the attached screenshot. While a lake maybe once or twice per biome transition is reasonable, vanilla spawn-rates are a bit overzealous.

**Describe the solution you'd like**
In the "feature settings" screen for world gen, could we have an option to change the spacing of these water features?

**Additional context**
https://i.imgur.com/yvY9CJF.jpg - Too many small lakes can end up looking like craters on the landscape.

**Comment by dags-** [comment]
Placement rate/spacing is as vanilla. Could be altered via a feature config json in a datapack (documentation for which is in the works).
