### ISSUE TITLE
Delta [River Type]

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#130]
**Is your feature request related to a problem?**
As rivers stand right now they're nothing more than a starting point inland that turns into a squiggly line all the way down towards the ocean. They all look down right the same no matter what type of biome or terrain they go through.

**Describe the solution you'd like**
Whenever land meets ocean a river delta would have a chance to function as a buffer zone between the continental and oceanic terrain types. The river delta would start out from the parent river several blocks (for example 250m - 500m) away from the ocean, creating smaller rivers on the sides that would keep branching out eventually reaching the ocean.

**Describe alternatives you've considered**
There are no alternatives I have considered. This may be subject to change.

**Additional context**

River delta example
![afbeelding](https://user-images.githubusercontent.com/19509275/78458844-ba4caf00-76b4-11ea-8b11-004d039de99d.png)

This Feature request is tied to issue #80

**Comment by dags-** [comment]
I have no plans to add this

**Comment by ZenTauro** [comment]
If I was to implement this, would you be willing to merge it?

**Comment by dags-** [comment]
I'd take any PR's into consideration
