### ISSUE TITLE
Estuary [River Type]

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#131]
**Is your feature request related to a problem?**
As rivers stand right now they're nothing more than a starting point inland that turns into a squiggly line all the way down towards the ocean. They all look down right the same no matter what type of biome or terrain they go through.

**Describe the solution you'd like**
Whenever land meets ocean a river estuary would have a chance to function as a buffer zone between the continental and oceanic terrain types. The river estuary would start out from the parent river several blocks (for example 250m - 500m) away from the ocean, creating an estuary that would  widen (the estuary width varies between rivers) eventually reaching the ocean.

**Describe alternatives you've considered**
There are no alternatives I have considered. This may be subject to change.

**Additional context**

River estuary example
![afbeelding](https://user-images.githubusercontent.com/19509275/78459442-4f51a700-76b9-11ea-933f-706edacd63a3.png)

This Feature request is tied to issue #80

**Comment by dags-** [comment]
I have no plans to add this specifically. Seeing as though rivers do taper wider towards the end this kind of occurs anyway
