### ISSUE TITLE
BoP

### ISSUE THREAD

**Issue by FatOldFiora** [TerraForged/TerraForged#132]
Terraforge  does not create the world with Biomes o Plenty biomes, but i found some items from the mod around like mushroom.
i tried downloading the Nature Finder mod to be sure and it didnt show a single BoP biome.
how can i fix that?

**Comment by demonJ5** [comment]
By default TerraForged should integrate custom biomes into the worldgen; this is a BOP "grove" in my world.
https://i.imgur.com/2FzBUsK.jpg
Have you messed with the Terraforged settings at all? Maybe you could try setting them to defaults.

**Comment by FatOldFiora** [comment]
Nope,didnt touch the settings

**Comment by Quizer9O8** [comment]
Try `/terra locate bop:grove` or something.

**Comment by FatOldFiora** [comment]
Ok, i simply tried reinstalling everything for the third time and now it work fine
aaah good ol' craft

thank you everybody
