### ISSUE TITLE
TerraForged World Gen ignores Biome Blacklist of other mods

### ISSUE THREAD

**Issue by TheUntamed** [TerraForged/TerraForged#136]
**Description**
When TerraForged World Gen is selected Structures generate and mobs spawn in Biomes that are blacklisted for those structures/mobs.
I tested this with the Dungeons of the mod _Dungeon Crawl_ and the mobs of the mod _Lycanites Mobs_
Both mods have a biome blacklist in their config. Dungeons for example are not supposed to generate in (Deep) Ocean Biomes and the Arisaur and Maka are not supposed to spawn in Planes Biome but they do with TerraForged World Gen.

I of course tested it with default world generation and as far as i could see neither the Dungeons or mobs generated/spawned in the blacklisted biomes.

**Additional information**
Both mods I tested had the blacklist in the config file. I don't know if that's important because I didn't change the default configurations of those blacklists.

**Comment by dags-** [comment]
What version of TerraForged are you running?

There was a bug with biome position lookups in an early version of TF which other mods might use to determine if something should place/spawn. That was fixed around version 0.0.3

Otherwise, TF just uses the mobs/structures that have been added to biomes just like the vanilla generator would. Not sure why these mods' blacklisting systems would not work normally

**Comment by TheUntamed** [comment]
Version 0.0.12 (latest)

**Comment by dags-** [comment]
For the dungeons mod; a dungeon won't start in an ocean biome but can extend into one if started in a nearby whitelisted biome.

This is true for vanilla gen too:
![2020-04-06_11 20 05](https://user-images.githubusercontent.com/4276064/78552224-03a91580-77ff-11ea-9f03-b06135383dce.png)

----

Lycanites Mobs doesn't appear to add their mob spawns to biomes as vanilla does so I assume they are handling spawning in their own custom way - in which case I think it'd be up to them to address

**Comment by TheUntamed** [comment]
Interesting. I thought the Dungeon Biome is defined by the tower.
