### ISSUE TITLE
Removing Biomes

### ISSUE THREAD

**Issue by Scarecrow-01** [TerraForged/TerraForged#137]
Will there ever be a way to just prevent certain biomes from spawning?
It would be nice to be able to get rid of some of them directly without having to mess with the humidity levels.

For example, I was looking to make a tropical world and I have achieved my goal by bumping up the humidity.. this also generated several swamps tho. It would be really nice to be able to add certain biomes to a "blacklist" thus preventing them to ever generate in your world :D

**Comment by Jokkaj** [comment]
True, it would be nice

**Comment by dags-** [comment]
https://github.com/TerraForged/TerraForged/issues/20
