### ISSUE TITLE
Will this be back-ported to older Minecraft versions?

### ISSUE THREAD

**Issue by WARRENHARPER1993** [TerraForged/TerraForged#14]
Will this exclusively be available on 1.15? From the screenshots, it looks like a really unique world generator. I have never seen terrain this good. So I wonder if it will ever be ported to other (potentially older) versions?

**Comment by dags-** [comment]
I can appreciate the reasons that keep users on older mc versions but it's not pratical for me to back-port, maintain & support multiple versions.

My aim will be to keep current with forge.

**Comment by Reshirou** [comment]
Use ATG, or RTG in place of this for older versions

RTG goes for more beauty and less, I guess flat-world, so youll have a harder time to build a huse

ATG is not quite as pretty, but much more flat terrain so you can build


I know TF seems to be a nice inbetween of the two, best of both basically, buuuuut the other two are more than good enough replacements =)
