### ISSUE TITLE
Terrain Type Mode

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#142]
**Is your feature request related to a problem? Please describe.**
TerraForged is missing the 'Terrain Type' mode in the customization section.

**Describe the solution you'd like**
Terrain Type would show you different types of terrain in the seed preview window.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by dags-** [comment]
A different colour per region like the biome view?

**Comment by Quizer9O8** [comment]
Something like that yes. Whenever I crank up the sliders it is kinda hard to see what changes the region actually has gone trough...

**Comment by dags-** [comment]
Added to 0.0.14
