### ISSUE TITLE
[Feature Request] Compatibility for modded stones

### ISSUE THREAD

**Issue by i-o-u** [TerraForged/TerraForged#143]
**Is your feature request related to a problem? Please describe.**
Modded stones [namely Quark's] aren't a part of Terraforged's world gen

**Describe the solution you'd like**
It would be nice if maybe there was a way to integrate stones with forge tags or just directly add compatibility
**Describe alternatives you've considered**
Idk you could just not I can't really tell you what to do lol

**Additional context**
![2020-04-15_22 53 09](https://user-images.githubusercontent.com/60834747/79339339-14c6f480-7f6c-11ea-8d04-8bffa25c91f8.png)
What a mountain with Quark stones looks like. The light stone is marble and the dark is slate.

**Comment by dags-** [comment]
This is already supported.

It's up to other mods to add their blocks to the tags if they want to (I've kept them quite generalised so other worldgen mods can make use of them too).

https://github.com/TerraForged/TerraForged/wiki/Mod:-Tags:-Blocks

I'm also working towards being to do it via a datapacks so users can do it themselves more easily.

**Comment by bastientanesie** [comment]
I'd like to point out that, while TerraForged is compatible with Quark (and others), disabling custom stones in your `minecraft/config/quark-common.toml` won't affect TerraForged' mapgen, which result in Quark's new stone blocks still being generated by TerraForged...

Is there any way of dealing with this @dags-? I'd really like to play with TerraForged and Quark but I don't want/need Quark's stone to be generated 😞.
Generating a "normal" world works just fine, so I guess it as to do with TerraForged?

**Comment by dags-** [comment]
(The quark-common config file is quark's not mine)

There are two approaches you could take:

1. disable the 'strata decorator' in TF's world-gen settings - this would disable all rock layers (vanilla and quark) and only generate stone + blobs of other stone types.

2. you could edit the wg_stone.json file in quark's jar and remove the stone types you don't want.

**Comment by bastientanesie** [comment]
I'll try and disable the strata generator. If this works then it means that it's on Quark's side as I properly disabled all of its custom stones in its config file (not blaming you BTW).

If this works then i'll try your 2nd option as I'd like to keep your strata generation, it just looks too cool to be disabled ^^.

Thanks for your quick reply, and keep up the good work! I checked all your planned features/enhancements and boy this looks promising!
