### ISSUE TITLE
Mine and Slash oregen

### ISSUE THREAD

**Issue by Blank517** [TerraForged/TerraForged#144]
**Description**
TerraForged world generator block your ore generation. I already tried with "Strata Decorator" option enabled and disabled.

**How to reproduce**
1. Add these mods:
https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded/files/2930272
https://www.curseforge.com/minecraft/mc-mods/curios/files/2913518
2. Generate a world
3. Mine and Slash's ores are not generated.

**Comment by dags-** [comment]
Are you sure you don't have another mod that might be blocking it?
Works fine with just TF and those 2 mods.

Strata Enabled:
![2020-04-15_21 43 49](https://user-images.githubusercontent.com/4276064/79386564-3ae79700-7f62-11ea-9e02-bf8b7c400c56.png)

Strata Disabled:
![2020-04-15_21 40 39](https://user-images.githubusercontent.com/4276064/79386295-d593a600-7f61-11ea-95f4-0607a4e3fc6e.png)
