### ISSUE TITLE
Recommendation: A template users can send to developers of Biome mods to explain the Overworld type

### ISSUE THREAD

**Issue by noobanidus** [TerraForged/TerraForged#145]
I got a lot of garbled info and a bit of a garbled bug report for Traverse talking about an Overworld BiomeDictionary *tag* which confused me, and another person in the channel suggested it might be to do with Vanilla. I haven't had much time to deal with it recently (especially as I wasn't the one responsible for the 1.15.2 port), and someone else asked for a status update -- as they'd mistakenly been told that we were sitting on a fix. (I was still waiting for some Maven shenanigans to be resolved.)

Regardless, I've looked into the issue now, and I finally understand what the problem is. In order to make it easier for people to report this issue to *other* mod developers, I thought I'd offer a simple template "report" concept that might help, especially given this Overworld type is "brand new" (in terms of Forge) and only got added at the tail end of last year.

Example:

```
Hello!

Forge recently added [the Overworld BiomeDictionary type](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L99), with the recommendation that it be applied to any biome that can spawn in the Overworld. This complements the End and the Nether types, and not having any of these three types indicates that a biome is only to be spawned in a modded dimension.

TerraForged (a terrain generator) for 1.15.2+ uses the overworld Biome Dictionary type to determine which biomes are suitable for placement. Unfortunately, as your mod doesn't implement these types when adding biomes to the dictionary, your mod's biomes cannot be placed by the generator.

Thankfully, fixing this is as simple as adding `BiomeDictionary.Type.OVERWORLD` to each biome designed to spawn in the overworld.
```

Hope this helps!

---

The actual message: Hello!

Forge recently added [the Overworld BiomeDictionary type](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L99), with the recommendation that it be applied to any biome that can spawn in the Overworld. This complements the End and the Nether types, and not having any of these three types indicates that a biome is only to be spawned in a modded dimension.

TerraForged (a terrain generator) for 1.15.2+ uses the overworld Biome Dictionary type to determine which biomes are suitable for placement. Unfortunately, as your mod doesn't implement these types when adding biomes to the dictionary, your mod's biomes cannot be placed by the generator.

Thankfully, fixing this is as simple as adding `BiomeDictionary.Type.OVERWORLD` to each biome designed to spawn in the overworld.

**Comment by dags-** [comment]
Ah yes sounds like a case of poorly relayed information. I'll add something to that effect on my wiki faq so people have something to link to rather than relying on them to recite something correctly.

**Comment by noobanidus** [comment]
No worries! I just figured it would save everybody some confusion. I look forward to trying TerraForged out (possibly on the next DevCraft once ... I update my mods to 1.15.2).
