### ISSUE TITLE
Needs more gravel

### ISSUE THREAD

**Issue by Artellia** [TerraForged/TerraForged#147]
I'd love to see more gravel generate on the surface. Especially with the coming changes to the nether which will somewhat lessen the large deposits there, having at least a few massive areas of gravel to pair with beach/desert sand for concrete is important to some builders. I suggest more gravel beaches and gravel on mountains. Maybe tie it into the erosion feature?

**Comment by dags-** [comment]
Gravel can be found:
- gravel beaches
- river and ocean beds
- in strata layers or in (vanilla) pockets when strata is disabled
- on mountains/cliffes where erosion has occurred
