### ISSUE TITLE
Froze When Trying to Create Desert World

### ISSUE THREAD

**Issue by TrueDakkon** [TerraForged/TerraForged#148]
So I was trying to make a dessert world(no water or anything else) using the mod, and upon trying to generate the world, it froze up and required me to restart it. Yes I did wait. Left it over night for a full 8+ hours and it didn't load any more than it already had.
The settings I had were as followed:
Sea Level: 0
Ocean Size: 0
Continent Scale: 10000
Moisture min/max: 0
Temperature min/max: 1
Everything in the River Settings set as low as they can be.

Log file:
[Pastebin](https://pastebin.com/4VXSn51D)

**Comment by dags-** [comment]
Something to do with DungeonCrawl - probably isn't expecting ground level to be at 0
