### ISSUE TITLE
Water generating incorrectly in swamps

### ISSUE THREAD

**Issue by TrueCP6** [TerraForged/TerraForged#149]
Occasionally in swamps water generates in a way that it shouldn't (I don't know how to describe it)
![Screenshot](https://user-images.githubusercontent.com/39642832/79692042-31f90d00-8263-11ea-881e-ab35496a8f9f.png)

It can be found at `/tp @s 1450 69 713` on [this world](https://github.com/TerraForged/TerraForged/files/4499582/Water.bug.zip). It may be due to lowering the sea level to 60 blocks. If the world is regenerated with seed `1816881894` and no options changed the problem does not occur.

**Comment by dags-** [comment]
Another case of Mojang hardcoding the water level :[
I'll try adding a replacement

**Comment by Barerock** [comment]
I don't even GET swamps. No results in 24,000 samples using Nature's Compass.

**Comment by dags-** [comment]
Yeah don't worry it's being addressed in the upcoming 0.1.0 version of the mod
