### ISSUE TITLE
Will the mod ever be available on 1.16 when it comes out?

### ISSUE THREAD

**Issue by Jackrin** [TerraForged/TerraForged#150]
I planning on starting a forge server with this, mod. But i will also update to 1.16 when it's released. So is there any intention of making this mod 1.16 in the future?

**Comment by dags-** [comment]
Yep probably.

The only reason not would be if 1.17 comes out before Forge has updated to 1.16 and they end up targetting that instead (in which case I'd likely jump straight to 1.17). I have no reason to believe this would happen but something similar happened with 1.13 and 1.14 so it's still fresh in memory.

**Comment by dags-** [comment]
I'd add though that I'm currently working on some large changes for the 0.1.0 version of TerraForged which will break cohesion with existing 0.0.x worlds (ie new chunks produced by 0.1.0 will not be seamless with those made on 0.0.x)

**Comment by TekExplorer** [comment]
1.16 is out on both vanilla and forge. is the mod going to be or is in the process of being updated?
is there something like this for the new nether? i feel like nether generation is really akward
