### ISSUE TITLE
Command permissions on multiplayer server

### ISSUE THREAD

**Issue by WillDereham** [TerraForged/TerraForged#151]
I am running TerraForged on 1.15.2 on a standard forge server, is there any way I can allow access to the `/terra locate` command to ordinary players? I haven't been able to find any forge-based permission mods, because i understand that permissions are something that are usually handled by plugins. I would be grateful for any help on this.

**Comment by dags-** [comment]
Forge does has a basic api for permissions that I could look at using. You'd need to find a mod that does the actual management of permissions (like Permissionsex/LuckPerms on Bukkit/Sponge)

**Comment by dags-** [comment]
Supported added in 0.0.13.
Permissions can be found [here](https://github.com/TerraForged/TerraForged/blob/master/TerraForgedMod/src/main/java/com/terraforged/mod/command/Permissions.java) for now
