### ISSUE TITLE
[1.15.2] Crash on world creation

### ISSUE THREAD

**Issue by dreckz** [TerraForged/TerraForged#154]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
Upon attempting to create a world, the client crashes from attempting to create the new world.

**How to reproduce**
The crash was somewhat reproduceable since it didn't happen 100% of the time.

**Additional information**
Crash Log:
[crash-2020-04-28_15.15.54-server.txt](https://github.com/TerraForged/TerraForged/files/4548398/crash-2020-04-28_15.15.54-server.txt)

**Comment by dags-** [comment]
A biome feature provided by one of those other mods is set up wrong and causing TF to crash.

If you could link me to the modpack (or zip the mods and send me them) I could probably find which one is the problematic mod.

**Comment by dreckz** [comment]
Is there a way that I can PM you it?  It's a custom pack that hasn't released publicly

**Comment by dags-** [comment]
Yeah sure. You can contact me on [discord](https://discord.gg/KwNtH5N) or through a curseforge private message if you prefer
