### ISSUE TITLE
Can't find any deserts

### ISSUE THREAD

**Issue by Mendax-tech** [TerraForged/TerraForged#158]
I have tried creating several worlds lowering moisture and raising temperature but only biome I can find is either a mesa or savannah. The strangest thing that deserts are shown in generation preview but are not there when I fly to their supposed location. Am I doing something wrong or deserts are not implemented yet?

**Comment by dags-** [comment]
Deserts only occur at low elevations and transition into mesa at higher elevations. This coupled with the requirement for high temperature and low moisture make them quite rare currently. It's being worked on for version 0.1.0
