### ISSUE TITLE
Custom oak tree model not generating in plains biomes

### ISSUE THREAD

**Issue by dirt-worm** [TerraForged/TerraForged#159]
For some reason, in the newer versions of TerraForged I only ever see oak trees with the vanilla model generate in plains biomes. In older versions this was not the case, and I really liked the custom oak tree models that this mod provides! All other tree models are unaffected, and oak trees spawning in forest biomes do not have this problem.

My question is: is this intentional or a bug? What can I do to get the custom oak trees spawning in plains again?

**Comment by dags-** [comment]
That was only in 0.0.12. Addressed as of 0.0.13
