### ISSUE TITLE
Biome Types: Mangrove Forest

### ISSUE THREAD

**Issue by quantum-ranger** [TerraForged/TerraForged#160]
_Please take a look through the [existing enhancements](https://github.com/TerraForged/TerraForged/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aenhancement+) to see if yours has already been suggested. Feel free to add your own thoughts to the thread :)_

**Is your feature request related to a problem? Please describe.**
My suggestion is not necessarily related to a problem, but would add to the variety of custom biomes utilizing only vanilla blocks in TerraForged. You seemed to imply on the TerraForged Discord server that you were going to add new biomes, such as the Fir Forest, so I would like to give you some ideas for the far future of the mod.

**Describe the solution you'd like**
The Mangrove Forest biome would be a tropical swamp biome which would feature custom mangrove trees made up of birch or acacia wood. Acacia wood would be my primary recommendation, because while the exterior bark of a mangrove tree is grey, the inside of the log when split is brown or orange. Unlike vanilla swamp biomes, the Mangrove Forest biome would generate only in warm regions, and would appear more often at coastlines and estuaries than at inland water sources.

**Describe alternatives you've considered**
There is no alternative to the suggestion. It is your choice if you would like to implement the suggestion in the far future of the mod or not.

**Additional context**
Here are pictures of mangrove trees growing near water/beaches to give an idea of how they might look.
![image](https://user-images.githubusercontent.com/64669527/80850808-dd9f4700-8beb-11ea-8c05-864248c1d833.png)
![image](https://user-images.githubusercontent.com/64669527/80850811-e728af00-8beb-11ea-8b5b-c3898bc77714.png)
![image](https://user-images.githubusercontent.com/64669527/80850825-01628d00-8bec-11ea-9be1-801eb365ab2a.png)

**Comment by dags-** [comment]
Not taking biome requests at this time
