### ISSUE TITLE
Stronghold spawns just being a big ravine?

### ISSUE THREAD

**Issue by CliffordH123** [TerraForged/TerraForged#161]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
So I have been playing on a world and got the point where I could go find a stronghold. I went to where the stronghold was according the the ender eyes and it just pointed to a huge set of ravines that spawned in each other. After getting frustrated I switched to creative and just went to town with my fist. There was no stronghold. I started a new world to see if I had gotten unlucky and the same thing happens. Repeat this several times I did.

**How to reproduce**
- Standard Forge Server
- No other third-party mods
- Start a world and go find a fortress through use of Ender Eyes.

**Comment by dags-** [comment]
Provide versions and logs pls
