### ISSUE TITLE
Sink Holes

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#162]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Sinkholes varying in size that can go deep under the ground. Some are connected to caves, filled with water, interconnected with each other or are just a straight up hole. These sinkholes have a chance to spawn anywhere in the world. Areas with the most moist precipitation and climate zones from Cold -> Temperate  -> Warm are more likely to have sinkholes.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
![zacaton_sinkhole](https://user-images.githubusercontent.com/19509275/80939670-a6908780-8ddd-11ea-86e7-a3f361a41268.jpg)
![China-sinkholes-1205866](https://user-images.githubusercontent.com/19509275/80939721-ce7feb00-8ddd-11ea-9720-cbfb42483beb.jpg)

**Comment by zeydOpr** [comment]
I have encountered similar terrain next to an ocean. A cave connected the ocean and a hole filled with water. Since it was not an hardcoded terrain, it was small and not deep enough to be classified as a proper sink hole indeed. I will attach a photo.

**Comment by zeydOpr** [comment]
![2020-07-15_00 00 25](https://user-images.githubusercontent.com/52921941/87477221-71e84a00-c630-11ea-874d-e0e9256e2a7c.png)
![2020-07-15_00 14 21](https://user-images.githubusercontent.com/52921941/87477237-77de2b00-c630-11ea-949f-915a6fc78412.png)
