### ISSUE TITLE
Shallow rivers generate deep ocean biomes

### ISSUE THREAD

**Issue by SuperCoder7979** [TerraForged/TerraForged#163]
**Description**
Shallow rivers generate deep warm ocean biomes inexplicably.

**How to reproduce**
Make a world with just TerraForged v0.0.13 with the seed `-8307868405864224230`, teleport to [1094, 100, 840] or [1438, 100, 957]

**Additional information**
![image](https://user-images.githubusercontent.com/25208576/81029521-518f5880-8e53-11ea-88a8-1a7d7717d136.png)

This is the first time I've come across this isssue but I'll additional seeds/locations if I find them.

**Comment by dags-** [comment]
Weird. River biomes _can_ be overriden by oceans when they come into proximity due to the way river-gen approximates where the river should terminate. Deep ocean variants shouldn't though :/

I've re-written river-gen locally so hopefully this has gone away now but I'll keep an eye out

**Comment by dags-** [comment]
Should be fixed in 0.0.15
