### ISSUE TITLE
Option to Restrict Spawn Location

### ISSUE THREAD

**Issue by J-Stutzmann** [TerraForged/TerraForged#165]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Option to restrict initial spawn location based on biome, terrain type, temperature, and/or moisture.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by dags-** [comment]
No plans for this. Can be achieved via commands (`/terra locate` and `/setworldspawn`)
