### ISSUE TITLE
Ores don't spawn on modded stone layers

### ISSUE THREAD

**Issue by HermeticPrince** [TerraForged/TerraForged#167]
As the title says, ores are not spawning on custom stone layers such as the quark ones, or the ones i've manually added. 
At first i thought this was just a impression, but after generating the same world twice i've noticed that when a cave near the spawn was on a granite layer it had multiple visible ores, but when the same cave was generated on a quark stone layer it didn't any.
Is this a bug? or to make sure ores spawn on different layers a config other than the wg_stone.json file must be edited? Thank you.

**Comment by dags-** [comment]
Vanilla hardcodes the stone-types that ores can be placed in so I'll need to come up with a work around using the block tags.

Presumably ores spawn in quark's stone types in non-TF worlds?

**Comment by HermeticPrince** [comment]
to be honest i never noticed if they do, since while the stone "clusters" are bigger than vanilla, they're not as big as the TF strata layers.

**Comment by dags-** [comment]
Ah. Well I can probably add support in the future. For the meantime you can just travel to an area that has different strata or disable the layers altogether if you want something more vanilla

**Comment by dags-** [comment]
Added to 0.0.14
