### ISSUE TITLE
Post-Generation erosion - placing water -> Creeks

### ISSUE THREAD

**Issue by AdamM72** [TerraForged/TerraForged#169]
_Please take a look through the [existing enhancements](https://github.com/TerraForged/TerraForged/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aenhancement+) to see if yours has already been suggested. Feel free to add your own thoughts to the thread :)_

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to be able to place a water block on a slope and have it 'erode' it's own water course over time.
**Describe alternatives you've considered**

**Additional context**

**Comment by dags-** [comment]
There's already a mod for this:
https://www.curseforge.com/minecraft/mc-mods/water-erosion

You might need to enable 'vanilla water features' in TF settings so that springs get placed
