### ISSUE TITLE
terraforged still uses disabled stones

### ISSUE THREAD

**Issue by wackoamd1** [TerraForged/TerraForged#173]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
with quark new stone option disabled , terraforged still uses the quark stone ,
however when i disable the strata option in terraforged , it works like it should not a quark stone in sight. , i really like terraforged but looking at the issues it overwrites a shitload op mods/configs

**How to reproduce**
install quark , turn off the new  types and gen a new world with enabled strata in terraforged

**Additional information**
TerraForged-1.15.2-0.0.13
Quark-r2.1-235
Forge 31.1.77

**Comment by dags-** [comment]
you'd need to remove the stone types you don't want from quark's 'wg_stone' block tag (in their mod jar)
