### ISSUE TITLE
Biomes o' plenty nether compatibility

### ISSUE THREAD

**Issue by disastercube** [TerraForged/TerraForged#179]
Many world generation mods have biome's o plenty nether compatibility, meaning even if you chose a world generation that's not biome's o plenty you will still get nether biomes from the mod. It would be really nice to have this feature in TerraForged as well since 1.15.2 nether is basically empty and it would provide much more excitement while exploring it. That said it only doesn't work with nether. You can still get a mix with biome's o plenty and TerraForged in the overworld but only there.

**Comment by dags-** [comment]
There's an option for this on version 0.0.14
