### ISSUE TITLE
Trees not removing saplings from world when grown.

### ISSUE THREAD

**Issue by McMasterx** [TerraForged/TerraForged#18]
**Description**
Trees grown naturally, not with bone meal, form the logs, but break the sapling without removing it from the world. 

**How to reproduce (get your mind out of the gutter! -_-)**
Just letting trees grow naturally

**Additional information**
¯\_(ツ)_/¯

**Comment by dags-** [comment]
Oh... that's dumb. Thanks for reporting!

**Comment by McMasterx** [comment]
The funny way that I discovered it was after setting randomTickspeed to 3000, and having to ask where all the extra saplings were coming from. 
Also, grown trees seem to be growing down an extra 2-3 blocks, I've started to notice.

**Comment by dags-** [comment]
The growing downwards thing is intentional - mostly for worldgen so you don't get odd-looking overhangs on larger trees placed on slopes.

I could probably cancel this behaviour for trees grown during normal gameplay, or at-least provide a config option for it

**Comment by dags-** [comment]
This should be fixed in the next release
