### ISSUE TITLE
Different strata styles

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#180]
**Suggestion:**
Make use of different strata algorithms to alter the style of strata generated throughout the world.

**Reference:**
https://www.icgc.cat/en/Citizens/Explore-Catalonia/Atlases/Geological-atlas-of-Catalonia/The-geological-cross-sections

and

https://www.isgs.illinois.edu/achievements/september/map-geologic-cross-sections-across-mahomet-bedrock-valley-now-available

**Example:**
Here's something resembling different geological cross-sections
![afbeelding](https://user-images.githubusercontent.com/19509275/81970997-b0f22300-9620-11ea-9c7f-386a0e0416e6.png)
![afbeelding](https://user-images.githubusercontent.com/19509275/81971135-e565df00-9620-11ea-97e8-f834a21217b1.png)

**Comment by dags-** [comment]
Wouldn't be worthwhile enough and likely too slow
