### ISSUE TITLE
Table Mountains

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#181]
**Is your feature request related to a problem?**

This is not related to a problem but more an addition to the small group of existing terrain types.

**Describe the solution you'd like**

An additional "Table Mountains" terrain type could be implemented, similar to mountains, dales, or plateaus.

Geographically, it would be similar to Mountains at the base of the foothill albeit with more steep cliff faces that varies in steps. The very top of the mountain would be practically flat allowing you to look over the surrounding terrain.

**Describe alternatives you've considered**

See "More climate controls to allow biasing of certain conditions [#87](https://github.com/TerraForged/TerraForged/issues/87)"

**Examples**
![afbeelding](https://user-images.githubusercontent.com/19509275/81977284-11399280-962a-11ea-8e5c-da82dad03ab4.png)

![afbeelding](https://user-images.githubusercontent.com/19509275/81977453-552c9780-962a-11ea-8f95-8001dafc4d73.png)

**Comment by zeydOpr** [comment]
I have encountered similar or even exactly this terrain with 0.0.x and 0.x.0 several times. I will provide an example as soon as I can.

**Comment by zeydOpr** [comment]
![2020-07-14_23 22 56](https://user-images.githubusercontent.com/52921941/87472955-71988080-c629-11ea-90cf-9fb895d2a325.png)
0.1.0-BETA-1 Default

![2020-07-14_23 55 44](https://user-images.githubusercontent.com/52921941/87475535-a575a500-c62d-11ea-89ba-4fc20fdb9c9f.png)
0.1.0-BETA-4 Default
