### ISSUE TITLE
Ocean improvement 

### ISSUE THREAD

**Issue by disastercube** [TerraForged/TerraForged#184]
Oceans are definitely in need of improvement. This mod ads a vast variety of greens on land but in comparison oceans are a giant dead mess. It is true that this mod has one of the best world generated oceans out there but being so big it definitely needs some living content besides kelp and sea grass spammed on the ocean floor. For starters, warm oceans and coral reefs are on of the rarest biomes in the game, so rare in fact that I am questioning their existence since I've never seen one. By adding simple things like corals, natural stone structures, underwater cave systems with illumination (sea pickles...) and such thing would not only improve the game dramatically but also reduce the lag while building underwater. Because tall kelp is everywhere accumulated in groups, makes building underwater almost impossible and unrealistic (Lots of animated objects makes the screen freeze when placing a block or destroying it). By simply making some space between kelp and making it of different heights would make it far more natural and smoother. Natural stone structures could be used to also fill the space. Adding things like this would not only make this mod much more unique but also increase in popularity. 
A lot have tried to add ocean content to the game but so far only Mojang was able to make it with the unique vanilla vibe. But seeing how this mod is progressing it would be very much possible for a miracle to happen again.

**Here's some self built examples of stone structures and kelp generation :**

![2020-05-21_22 44 27](https://user-images.githubusercontent.com/62697421/82616241-f4becc80-9bcc-11ea-8c9f-caae3266cff2.png)

![2020-05-21_22 51 45](https://user-images.githubusercontent.com/62697421/82616278-0dc77d80-9bcd-11ea-8e20-1fe13282ffa2.png)

![2020-05-22_00 47 54](https://user-images.githubusercontent.com/62697421/82616295-2041b700-9bcd-11ea-9e70-b6b1872d26bf.png)

![2020-05-22_00 56 00](https://user-images.githubusercontent.com/62697421/82616348-39e2fe80-9bcd-11ea-86ac-4c492553fd98.png)

![2020-05-22_00 50 23](https://user-images.githubusercontent.com/62697421/82616329-2f286980-9bcd-11ea-83af-ea4a7bf84b2a.png)

![2020-05-22_00 56 08](https://user-images.githubusercontent.com/62697421/82616377-4c5d3800-9bcd-11ea-8280-08fe5a6f5409.png)

This structures would spawn more like a biome near the shore 1 / 2 below water to simulate real life oceans. Of course there could be more biomes which could differ from ocean depths. 

**Real life example:**

![Great-Barrier-Reef_Brendan-Rankine](https://user-images.githubusercontent.com/62697421/82616579-f1781080-9bcd-11ea-8e5a-77a304aafb05.jpg)

![coral-reef-travel-hero-136419594362102601-170717140828](https://user-images.githubusercontent.com/62697421/82616611-ffc62c80-9bcd-11ea-96f8-cbb08a7a268d.jpg)

![wave](https://user-images.githubusercontent.com/62697421/82616676-34d27f00-9bce-11ea-9173-c05c70b99ffa.jpg)

![activityphoto-e71c94de-e231-42bb-bd34-3ed8d9d01648](https://user-images.githubusercontent.com/62697421/82616692-3bf98d00-9bce-11ea-98c2-0d9a01c4a12b.jpg)

**Comment by dags-** [comment]
Not sure if you're using some funky worldgen settings but warm oceans are actually pretty common when get yourself in the appropriate climate band for them.

Anyways, I have an issue open already #12 for more varied ocean terrain which is something I will get to eventually.

Actually adding new ocean biomes is not really on my agenda though. There are plenty of mods out there that add biomes so my focus is on integrating those as best as possible. For example there'll be a way to configure weights of specific biomes coming to version 0.1.0

**Comment by disastercube** [comment]
It is true that there are some mods that add ocean content but none actually makes it realistic, vanilla or just naturally good looking in general. Your mod would be a perfect fit. It already ads more depth to it and all that it needs is some generated content or at least lag improvement. I have a solid gaming pc with 8gb of ram dedicated just for minecraft forge and whenever I placed a block further and deeper from the shore made my game drop from 300 to 2 fps. Besides the lag, wouldn't it look gorgeous if you stumped upon a realistic ocean. Those who are fans of building would definitely start making underwater bases.
