### ISSUE TITLE
Custom beach biomes buried under sand

### ISSUE THREAD

**Issue by HermeticPrince** [TerraForged/TerraForged#188]
Custom beach biomes added by mods (such as BOP or BYG) spawn with their custom sand material buried under normal sand, making the biome look like a default beach
At first i thought it was intended, since those biomes have small patches of their custom sand, but today i decided to dig through the normal sand and discovered that while the beach looks like a default beach, under the normal sand the actual biome was spawned
The beach shown in the pic is entirely a "white beach" from BOP. the square has been digged out to show which material the beach was supposed to be made of, which is hidden beneath normal sand. It isn't exclusive to this specific biome, since BYG adds multiple beach biomes and this issue happens with all of them. Thank you
![2020-05-24_23 45 31](https://user-images.githubusercontent.com/64935220/82773557-b9184280-9e18-11ea-8366-1baccd5af5ba.png)

**Comment by dags-** [comment]
Should be fixed in 0.0.15
