### ISSUE TITLE
Biomes

### ISSUE THREAD

**Issue by Sunekaer** [TerraForged/TerraForged#19]
**Description**
seems like the mod is using all biomes it can find in the registry, even tho there is dimension specific like biomes from https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge and https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep
And there is no config to blacklist biomes

**How to reproduce (get your mind out of the gutter! -_-)**
- install all 3 mods and open single player

**Comment by dags-** [comment]
Huh yeah. Fair point. I'll need to do something about that

**Comment by dags-** [comment]
I've added an initial fix for this which will be in the next mod version.
I do want to add more control over biome selection later down the line too.
