### ISSUE TITLE
Beach blending

### ISSUE THREAD

**Issue by disastercube** [TerraForged/TerraForged#190]
Some bigger beaches spawn without another layer of grass / snow on the sand and the two biomes don't blend nicely 

**Bad blending example:** 

![2020-05-28_11 06 47](https://user-images.githubusercontent.com/62697421/83123001-b9446680-a0d4-11ea-961e-5577fd01efeb.png)

**Good blending example:**

![2020-05-28_11 21 14](https://user-images.githubusercontent.com/62697421/83123648-76cf5980-a0d5-11ea-996c-00f20f0c5a20.png)

**Comment by dags-** [comment]
Have a look at the 'biome edge noise' settings if you'd like to change the transition.
(Helps to zoom in on the preview map and set the display mode to show biomes.
