### ISSUE TITLE
World cutting off and not generating anymore.

### ISSUE THREAD

**Issue by omegahai** [TerraForged/TerraForged#191]
Hi I cant find anyone else with this issue that has my circumstances so I figured I'd attempt posting it here. 

When I run a new world with Terraforged selected and installed(singleplayer), a big square generates with the terraforge generation but around it, nothing else generates. The world cuts off and no more chunks load in.

I've also for fun tried to upload worlds generated with terraforged from singleplayer into my realm, and that creates the same square, however this time normal vanilla minecraft generation generates around the square. 

Java Edition, Minecraft Launcher
1.15.2
Forge 1.15.2
Terraforged 1.15.2

**Other Mods I use:**

Optiforge 1.15.2
Optifine 1.15.2
Ambient Sounds 1.15.2
Xaero's minimap 1.15.2
+ SEUS Renewed shaders.

I've Increased render distance, Tried different performance settings, made many different worlds in singleplayer but the same thing happens every time.
I have NOT uninstalled and reinstalled the mod using the same world, and I've tried reloading chunks with F3+A, and lastly I've created a world, and sat down and waited for hours for it to finish rendering but it never does.
![javaw 2020-05-28 14-37-09-395](https://user-images.githubusercontent.com/66070185/83142409-c0796d80-a0f0-11ea-8e60-da26b63bb152.jpg)
![javaw 2020-05-28 14-33-30-610](https://user-images.githubusercontent.com/66070185/83142450-ce2ef300-a0f0-11ea-8b5e-7a556b1a637d.jpg)
![javaw 2020-05-28 14-34-55-017](https://user-images.githubusercontent.com/66070185/83142467-d38c3d80-a0f0-11ea-8e99-a2bf0f3399c3.jpg)
![javaw 2020-05-28 14-33-38-803](https://user-images.githubusercontent.com/66070185/83142475-d6872e00-a0f0-11ea-8116-708ee5a8d989.jpg)

 
I apologise if this has already been reported but I've been looking for a solution for weeks and I have not yet found anyone who has had the same situation.

**Comment by DohnJenver** [comment]
As realms can't use forge, any chunks which haven't been generated before uploading to your realm will default back to vanilla generation.

As with the chunk loading, I believe it's just an issue with Optifine not being fully complete so the only thing you can really do is wait for a proper release and make sure you are using the latest version of Optifing 1.15.2 (I believe it's pre8).

**Comment by dags-** [comment]
Yeah I've found that Optifine doesn't work with Forge unless you reduce the render distance to a Vanilla value (ie 1-32) **before** loading the world.

If you can recreate without Optifine installed then feel free to report here .
