### ISSUE TITLE
Adding thermal weathering (Scree and Talus)

### ISSUE THREAD

**Issue by DeltaTerrainz** [TerraForged/TerraForged#192]
Hello, I would like to see some things in TerraForged such as adding realistic thermal weathering, and it would improve the looks of biomes such as mesas and desert formations as it would add much more realism. Add thermal weathering would also improve how mountains look also.
![image](https://user-images.githubusercontent.com/66214148/83357117-74206e80-a338-11ea-9cf0-6ecd054a0e04.png)

**Comment by dags-** [comment]
The current erosion algorithm is already expensive. I've no plans to add a second
