### ISSUE TITLE
Example World Seed?

### ISSUE THREAD

**Issue by skellitor301** [TerraForged/TerraForged#193]
Hello, I've checked to see if this was answered already but I couldn't find it so here it is. I was on the Terraforged site and saw the example world at the bottom, and I was wondering if it's possible to currently get that world if we use the seed for that world? If so, could the seed be shared? That would be an amazing map to play on.

**Comment by dags-** [comment]
Not currently. That world was generated with an in-development version of the mod.
You'll be able to generate something similar in version [0.1.0](https://github.com/TerraForged/TerraForged/milestone/1) of the mod.

**Comment by skellitor301** [comment]
If I were to use the 0.1.0 version of this mod, and the seed, would there be any issues if I loaded up the world, preloaded the chunks, and then updated to the current version? Also, would modded world gen items like biomes'o'plenty and modded ores affect the 0.1.0 version or the update from 0.1.0 to current?
