### ISSUE TITLE
Texts on GUI is hardcoded and cannot be found in the language file

### ISSUE THREAD

**Issue by yezhiyi9670** [TerraForged/TerraForged#194]
**Description**

Texts on GUI is hardcoded and cannot be found in the language file. This is very bad for globalization. Technically, all non-debug displayed texts should be localizable.

**How to reproduce**

1. Select world type `TerraForged` on world creation screen. Click `customize` to make sure there are some texts on the GUI.
2. Navigate into the mod jar file. Open `assets/terraforged/lang/en_us.json`.  
❎ Texts seen in the GUI cannot be found here. This means they are hardcoded.

**Comment by dags-** [comment]
#155
