### ISSUE TITLE
Client Sided Crash with Popular Food Mods

### ISSUE THREAD

**Issue by ShockPuppet** [TerraForged/TerraForged#197]
[latest.log](https://github.com/TerraForged/TerraForged/files/4739831/latest.log)

**Description**
When using XL food or Pams Harvest Craft or Simple Farming mod on a server with terraforge, client disconnectes immediately when trying to connect

**How to reproduce**
- Using latest forge and minecraft 1.15.2 
- Install terraforge
- install any of the food mods listed above
- try to connect

**Additional information**
- Single player works fine
- Server loads and runs fine
- Error - Error presented to client: [06Jun2020 06:04:29.128] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: ShockkyAU lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by ShockPuppet** [comment]
I have a server with many mods, i spent around 4 hours checking them all with a combination of Terraforge and BoP, i didnt run into any hard crash/disconnect issues except for with the food mods listed in my post above. Other mods that add items to the world, such as Botania flowers and Fruit Trees by Snownee and the Flax that appears in plains biomes from Silents Gear had no problems whatsoever.

**Comment by dags-** [comment]
Is there anything that makes you think TerraForged is the cause of the problem? (I don't see anything in the log to suggest it is). Have you run the same setup without TerraForged installed?

Do the client logs from the same point in time give any further information?

**Comment by ShockPuppet** [comment]
The server was using xl food mod without issue for about a week in conjunction with the other mods. When Terraforge was added to a new world that was created (and it was the only new mod added), the issue occured. Removing xl food mod solved the client sided disconnect. As i really like terraforge I thought maybe xl food mod was the issue so i instead tried some other popular food mods such as pams and simple farming with new world creation and they all give the exact same error. The only mod that makes them display this error is when they are used on the server with terraforged. Without it, the client can connect fine.

**Comment by dags-** [comment]
Can you provide a log from the client after it has failed to connect please?

**Comment by dags-** [comment]
K, I've tested with all the listed mods (apart from Pams Harvest which isn't available for 1.15) and had no issues.

Either another mod is causing your problem, or as the server log suggests, you are missing some of the required mods on the client you're trying to connect with.
