### ISSUE TITLE
Inconsistent strata across same seed worlds

### ISSUE THREAD

**Issue by Windspren** [TerraForged/TerraForged#198]
### Please also look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported :)

----

**Description**
The seed used to generate stone strata layers is changed every time you restart minecraft, resulting in different strata patterns for multiple worlds with the same seed

**How to reproduce**
Create a new world and copy the seed. Close and restart minecraft, and create a second world with the same seed. The two worlds will have completely different stone layers.

**Comment by dags-** [comment]
Ah, this is because the list of each material type is left unsorted so the ordering may vary between restarts. I can fix this by sorting the material lists by name.

The shapes/numbers of layers are correctly seeded but the material selection is not.

**Comment by dags-** [comment]
Fixed in 0.0.15 (hopefully!)
