### ISSUE TITLE
Suggestion: Save Presets

### ISSUE THREAD

**Issue by TPL2008** [TerraForged/TerraForged#199]
It would be really nice if you could save presets because when you start in a bad  seed but want the same preset it is no nice having to do everything again, especially  if you made a lot of changes

Sorry if my English is wrong

**Comment by yurisuika** [comment]
You can already do this several ways.

1) Re-create the world from the world list and change the seed.
2) Delete a world's region folder and edit the seed in level.dat.
3) Use the Set Defaults button in the world creation menu and make a new world.

**Comment by dags-** [comment]
There's also `/terra defaults set` which can be run from inside the world to create a preset from it.
