### ISSUE TITLE
TerraForged Seeds

### ISSUE THREAD

**Issue by BNVDES** [TerraForged/TerraForged#200]
So i was going to use TerraForged to generate a world and then copy its seed to Vanilla Minecraft. However, i didnt know if that was possible, and would prefer to hear from the creators first. Does the mod need to be active while playing a TF generated world/seed or could i copy the seed and it would work normally in Vanilla?

**Comment by dags-** [comment]
No you would need to generate the world first and then copy the world data to the server

More info here:
https://github.com/TerraForged/community/wiki/Vanilla-Server
