### ISSUE TITLE
Use of Swamp Expansion Biomes with Terraforged swamp Generation

### ISSUE THREAD

**Issue by Bobisnotap** [TerraForged/TerraForged#201]
Swamp Expansion adds more content to pre-existing swamps and adds new types, and the changes to swamps that normally occur with Swamp Expansion apply, but the new swamp types do not generate in Terraforged worlds.

Support for these new swamp types in Terraforged would be ideal, as it increases the variety.

**Comment by dags-** [comment]
SE doesn't mark its biomes with the 'overworld' BiomeType so TF won't use them.
You can read more about that here:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes

It's a relatively new marker so their developer(s) might not be aware of it. I'm sure they'd add it to their mod if you ask -  feel free to point them to the above link if it helps explain the problem/solution
