### ISSUE TITLE
TerraForged ignoring other mods config

### ISSUE THREAD

**Issue by ZAKsPop** [TerraForged/TerraForged#202]
However I've got a strange problem. I also use a mod called Create. It has its own blocks such as limestone, gabbro, etc..

TerraForged seems to ignore the create config file. I have the config set to not generate some of these as they are only decorative. However Terraforged still generates them and in abundance. to the point of not generating common stone at all. It is very difficult to play without stone. This issue only happens when using terraforged worldgens.

**Comment by dags-** [comment]
You need to edit/remove create's wg_stone block tag file in its mod jar
`/data/foreg/tags/blocks/wg_stone.json`

Alternatively you can disable TerraForged's strata decorator to get normal stone generation

**Comment by lamoyrl90** [comment]
You could also create a data pack with a forge/tags/blocks/wg_stone.json that simply overwrites your modpacks' settings. That way you don't need to modify a .jar.
