### ISSUE TITLE
WorldPainter Compatibility

### ISSUE THREAD

**Issue by MattiBorchers** [TerraForged/TerraForged#203]
It would be cool if you could (continue to) generate a map with TerraForged with terrain that was created with WorldPainter.

The idea is: You create the elevation map, terrain and biomes with WorldPainter and let TerraForged generate the vegetation and structures. In Minecraft version 1.12 this process is called "population". In 1.15 the map generation process was further split up in the "status" tag of the region NBT file.

When I open a unpopulated map with TerraForged, my custom biome distribution gets overwritten by TerraForged.

**Comment by dags-** [comment]
This might be possible to support

**Comment by dags-** [comment]
Had a look into it but it won't be doable unfortunately.

Pretty much all of TerraForged's decoration stages are reliant on the additional height/climate/erosion/gradient (and various other) data maps that are generated by TerraForged. You're effectively bypassing all that information by providing your own base terrain so TF has no suitable data to do its decorating (ie you may as well use vanilla to populate)
