### ISSUE TITLE
[MC 1.15.2] Crash when loading world

### ISSUE THREAD

**Issue by winnetrie83** [TerraForged/TerraForged#205]
**Description**
I loaded my existing world and while loading it crashed. I tried this multiple times and it keeps crashing. 

**How to reproduce**
No idea, this was the first time i encountered this

**Additional information**
Crash information: https://pastebin.com/FknwkTHY

**Comment by dags-** [comment]
Need the full log.

Have you edited the mod's block tags?

**Comment by winnetrie83** [comment]
No i did not but i think it is datapack related. The datapack has nothing to do with terraforged btw.
