### ISSUE TITLE
Spigot/Paper Version

### ISSUE THREAD

**Issue by theminecoder** [TerraForged/TerraForged#21]
Is there the possibility for this to be eventually usable on spigot/paper servers? I am aware that currently the codebase is very tied to forge but with enough platform abstraction it would be possible.

There currently really isn’t they many good terrain generators for the plugin based community because they mostly rely on new block or they stuck with forge only, and I really do think this one could be one of the better ones.

**Comment by dags-** [comment]
TF Core is already a pretty major abstraction (it's pure java). The forgemod component basically handles biome and block selection and building up the chunks - this is still a pretty sizeable task but you're right that it's nothing that can't be done on other platforms.

I don't see myself working on port for the forseeable, but others are very welcome to take a crack at it.

**Comment by import-antigravity** [comment]
If anyone wants to do this I’d be willing to help.
