### ISSUE TITLE
Terraforged does not generate Druidcraft's Darkwood Forest

### ISSUE THREAD

**Issue by lamoyrl90** [TerraForged/TerraForged#211]
Terraforged doesn't seem to produce Darkwood Forests from Druidcraft. I generated multiple worlds, setting biome size to 50, and none of them had a Darkwood Forest within 10,000 blocks of spawn.

As soon as I generated a Default worldtype, I found one within 50 blocks of spawn.

Tested using Nature's Compass, Druidcraft 0.4.21 and Terraforged 0.0.14 on MC 1.15.2

I'm not sure whether the cause of this lies in Druidcraft or Terraforged, so I'm posting this to both mods' pages.

Druidcraft issues page post: https://github.com/MysticMods/Druidcraft/issues/49

**Comment by dags-** [comment]
Hi, thanks for linking the corresponding issue. I've responded there with the solution.
