### ISSUE TITLE
Create mod stone over generation

### ISSUE THREAD

**Issue by ReillyGregorio** [TerraForged/TerraForged#215]
**Description**
The mod Create when used with terraforged generation uses only the stone variants from the mod and replaces all stone. 
This destroys pretty much most biomes and also makes ores not generate.

**How to reproduce**
Minecraft 1.15.2, Forge 31.2.27 
Create and Terraforged installed and Worleys caves
Generate a new world using terraforged

Create mod:
https://www.curseforge.com/minecraft/mc-mods/create
Worleys caves:
https://www.curseforge.com/minecraft/mc-mods/worleys-caves

**Comment by dags-** [comment]
> uses only the stone variants from the mod and replaces all stone

Would you mind wording this another way please? Not sure what you mean.
NB you can disabled TerraForged's rock system by disabling the 'strata decorator' in the world gen settings.
