### ISSUE TITLE
Terraforged Tree Crash

### ISSUE THREAD

**Issue by Redspyboy8** [TerraForged/TerraForged#216]
----

**Description**
While playing Vahelsia 2.2.3, the game crashes if I go to a certain spot. The corrupted chunk is located near a lumberjack's hut from Minecolonies. I couldn't locate the specific chunk, but I could get a ballpark estimate. when I reload the game, the game doesn't crash again unless the chunk is unloaded and loaded again. 

**How to reproduce**
-run Vahelsia 2 2.3 using MultiMC
-load world 
-unload the problem area(if loaded)
-walk in general direction of problem area

**Additional information**

Crash Report: [crash-2020-06-29_15.54.54-server.txt](https://github.com/TerraForged/TerraForged/files/4848195/crash-2020-06-29_15.54.54-server.txt

Corrupted Area: ![Annotation 2020-06-29 145930](https://user-images.githubusercontent.com/67604353/86059417-b4a30300-ba30-11ea-84fd-0d9c32c9bf94.png)

modlist can be found in the crashreport

**Comment by dags-** [comment]
Should be fixed in 0.0.15
