### ISSUE TITLE
Chunks not loading past a certain radius

### ISSUE THREAD

**Issue by nikotsuru** [TerraForged/TerraForged#217]
It seems that nothing won't load past a 16 (or so, I didn't measure it) chunk radius. It does start loading again under some circumstances that I don't fully understand (I tried changing the allocated RAM, reloading the save and the game) but it goes back to not loading after some time (it can also lead to the save not loading any chunk anymore, so it might be more like corrupted at that point).

I have the latest release of OptiFine installed and I allocated more RAM but that's about it. My processor and graphics card aren't well suited for gaming but I've never had problems like this occur outside of this mod.

![2020-07-01_16 46 23](https://user-images.githubusercontent.com/32468556/86258344-037ca400-bbbb-11ea-8b87-8b37b3c74a6f.png)

**Comment by dags-** [comment]
I don't support optifine. If you can reproduce the problem without it installed feel free to open another ticket providing logs etc.
