### ISSUE TITLE
Generating non-overworld biomes.

### ISSUE THREAD

**Issue by Golrith** [TerraForged/TerraForged#219]
Is it possible (or add as a feature) to get TerraForged to generate biomes that only appear in other dimensions?

Perhaps a config where you can define custom biomes as types. e.g. myweirdmod:alienforest alias forest

I'm aiming to make a more "alien" overworld by picking and choosing biomes from other mods that don't normally generate in the overworld.

**Comment by dags-** [comment]
No plans for this
