### ISSUE TITLE
Is support for 1.16 planned?

### ISSUE THREAD

**Issue by Akulav** [TerraForged/TerraForged#220]
### Please also look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported :)

basically the title.

**Comment by dags-** [comment]
yes

**Comment by vico93** [comment]
Dont know if this was the issue who generated this FAQ on CF page:

> Regarding 1.16
You may be aware that Mojang are making some big changes to how world-gen works in the weekly snapshots. These
changes will eventually be released as version 1.16.2. The plan for TerraForged is to wait until that version has released
before updating the mod. Thank you for your patience.

But i want to throw my (non-technical) cents about it.

Mojang will add the [Custom world gen](https://minecraft.gamepedia.com/Custom) to 1.16.2. This will add a new button called "Import World", where the user can feed a JSON file for it and it will use that for the world gen parameters, both for overworld and to any dimensions accompanying the World (both vanilla, like nether or end, but also custom ones defined in the JSON). Full specification is in the wiki entry i linked below.

I dont know how Lex & co will implement Forge support for it, but i thought mainly in two points for 1.16.2+ Terraformed: 

First it would provide a custom generator type (alongside vanilla's `flat`, `noise` and `debug`), maybe terraformed:terraformed idk, so players/modpackers/serverops can make custom worlds/saves based on Terraformed's worldgen. If other mods who change worldgen (like BoP) get implemented "in the right way" they will seemingly get integrated with those JSON settings.

Second for the "Terraformed" world-type on the selection button (alongside DEFAULT, LARGE BIOMES, FLAT). I think this option for now are just predefined internal JSONs with the "default" settings for such worlds. So implementing the first point and you can have the second almost ready. Of course it also can have some options which will be just small tweaks in the predefined JSON.

Anyway i'm very exited to see how post 1.16.2 world gen mods will act, and if someday Galacticraft gets updated for 1.16.2+ as well and having similar (or extending) to the vanilla custom JSON system, i just imagine you can make a planet with default worldgen, other with Terraformed, other with terraformed+bop... anyway sorry for that ramble, nothing related to terraformed itself.
