### ISSUE TITLE
New vanilla trees in modded biomes

### ISSUE THREAD

**Issue by Sninctbur** [TerraForged/TerraForged#225]
TerraForged's new vanilla tree designs look _very_ good. However, non-vanilla biomes such as those from Biomes O' Plenty still generate the original trees for vanilla tree types, which can lead to somewhat jarring aesthetic transitions.

![2020-07-14_06 42 59](https://user-images.githubusercontent.com/29333347/87422406-369d3b00-c59e-11ea-88b8-ef70db48af68.png)

If the new trees can be generated in non-vanilla biomes, then the overall visual cohesion of TerraForged would improve.

**Comment by dags-** [comment]
Someone could make a datapack to achieve this. Modifying other mods' content to this extent is not within the scope of the project
