### ISSUE TITLE
Create & Quark stone variants ignoring wg_stone.json datapack

### ISSUE THREAD

**Issue by STOKE-STER** [TerraForged/TerraForged#227]
**Description**
I used a datapack to override which types of stone get the wg_stone.json tag. My intentions were to remove multiple of the same type of stone, for example limestone was generating from quark, create, and WTBW Decoration. I also wanted to remove all of the create stone types except for dolomite.
 
This is my datapack, which was placed in /config/terraforged/datapacks. I have verified there were no issues with the datapack by adding "minecraft:diamond_block", "minecraft:gold_block", & "minecraft:emerald_block". which then generated in the world.
[stratatest.zip](https://github.com/TerraForged/TerraForged/files/4935371/stratatest.zip)

I had a look through 3 jar files, Create, Quark & wtbw decoration. I found that Create has their own file adding the forge:wg_stone tag to their stone types. Replace=False so I don't think that should be interfering with my datapack should it? Seems like someone else had this issue, I haven't tried the mentioned craft tweaker work around yet but I'll look into it. https://github.com/Creators-of-Create/Create/issues/391
![create](https://user-images.githubusercontent.com/36657224/87741506-0537a000-c828-11ea-95c0-18e47206ee74.PNG)

Quark also has a wg_stone.json file however it's empty. Despite it being empty, I think they must be adding the tags some other way because when I changed my datapack to NOT include their stone variants, they still generated and had the tag. This change on their github was when it was changed to not have any blocks listed in the json file. https://github.com/Vazkii/Quark/issues/2053
![quark](https://user-images.githubusercontent.com/36657224/87741569-2ef0c700-c828-11ea-8d6b-d7f92b3b7558.PNG)

wtbw decoration didn't have any code or json file adding the wg_stone tag and as far as I can tell, disabling their stone types in their config file has worked to stop small clusters of marble and other types from generating.

It's apparent to me that however create and quark are adding the tags to their blocks, it's circumventing the datapacks settings? I'm by no means a java dev so I wouldn't even know what the issue could be but after trying to tackle this problem for the better part of 2 days I'm out of ideas.

**How to reproduce**
- Make a modpack with minecraft 1.15.2, Forge 31.2.30
- Add Create & Quark (& World stripper if you want to quickly cut away the chunks to view the strata layers, use this config too: https://pastebin.com/iGK05HnT)
- Place the attached datapack zip into /config/terraforged/datapacks
- Generate a world
- Blocks that haven't been specified will still generate

**Comment by dags-** [comment]
it's invalid json...

**Comment by STOKE-STER** [comment]
Oh shit, well that's embarrassing if that's the case, what's invalid about it?

**Comment by STOKE-STER** [comment]
oh the final line doesn't need a comma

**Comment by STOKE-STER** [comment]
🤦🏻‍♂️It worked. Cheers Dags 🤣
