### ISSUE TITLE
New Implements - Continents Distance and New Shapes

### ISSUE THREAD

**Issue by ProfessionaFiddler** [TerraForged/TerraForged#228]
Right now continent scaling is just a cornfield. My request would be:

- Gropuping continents (a chance for a continent to be flagged to downgrade distance to others)
- Stretching along longitude (random number between preset values for continent height)
- Macro noise for continents, inward and outward deformations (Manhattan 2.0?)
- Continent size randomity (along with scaling, min/max for random size)

Maybe save those as improvements for 1.17+?

**Comment by Quizer9O8** [comment]
For this to work we might have to dive in some form of plate tectonics. I've discussed this many times in the past but I honestly think it would be a good way going forward. I got a reference to a site where someone explains how they made plate tectonics work : [https://leatherbee.org/index.php/category/world-gen/](https://leatherbee.org/index.php/category/world-gen/)

As far as I know it seems pretty explanatory how to make a system that represents plate tectonics. 
Hopefully dags will give it a try.

**Comment by dags-** [comment]
I have no plans for this but I'll leave the ticket open if someone else wants a crack at it. Anyone that does should also be aware of river-gen's reliance on fast continent generation.

Re:tectonics
I think I've run out of ways of explaining why this isn't feasible in an infinite context like minecraft 😅  I'd suggest you have a go at using said explanatory materials to write something yourself; you'll either gain a greater appreciation of what's reasonable/possible or better yet show me the light and get the feature you want in the engine - win win!

**Comment by ProfessionaFiddler** [comment]
Yep, it has to feel realistic, recreating Earth core to manage continents would be overkill. Although minecraft is a great game, those plans can always be stored for future

**Comment by ProfessionaFiddler** [comment]
But still, now that you mentioned it, imagine how cool it would be - rebasing the mod onto semi-cubic chunks (2d chunks above sea level and cubic for underneath) and alter height limit to have beautiful terrain and even more splendid Earth core exploration. Thousands of meters underground, immense lava levels

**Comment by ProfessionaFiddler** [comment]
Sounds so big I would even involve patreon :D
