### ISSUE TITLE
Combine with Immersive Portals mod for world generation above 256 blocks

### ISSUE THREAD

**Issue by IgeNiaI** [TerraForged/TerraForged#230]
Hello.

There is a mod called Immersive Portals (https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge) that allows you to create seamless portals between any spots and even between dimensions. There is also a feature called "Dimension Stack" that utilizes the portals to stack one dimension over another almost seamlessly.

What do you guys think about using that mod to make worlds go above 256 height limit?

**Comment by dags-** [comment]
There are no plans to support this
