### ISSUE TITLE
Make use of the preview map's coordinates easier

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#233]
When previewing a potential seed for a world it might come in handy to pin down coords of a certain area without the need to constantly screenshot your screen. If you click somewhere on the seed preview screen a pin will appear on the exact coords. When switching render types (From Biome Type to Temperature) the pin will stay put. This would make comparing different render types with each other easier to spot differences when customizing the default preset.

**Current situation**
![afbeelding](https://user-images.githubusercontent.com/19509275/88436665-03ac4000-ce05-11ea-985f-1d420be14d90.png)

**New situation (With pin)**
![afbeelding](https://user-images.githubusercontent.com/19509275/88437590-1162c500-ce07-11ea-8c33-52baa95457a6.png)
 
**Pin**
![afbeelding](https://user-images.githubusercontent.com/19509275/88437650-35260b00-ce07-11ea-8325-145f70fffedd.png)

**Comment by dags-** [comment]
No but copy-to-clipboard functionality might be possible
