### ISSUE TITLE
Crash: Exception generating new chunk

### ISSUE THREAD

**Issue by JCLaHoot** [TerraForged/TerraForged#235]
**Description**
When exploring new chunks, the game crashes. This is a new behaviour, but it's hard to pinpoint exactly when this started happening (and what mod update it might be related to), since the explored world is relatively large and I havent had to load new chunks for a little while. I tried with + without Optifine and it doesn't change anything. I assume it's an issue with TerraForge, but it's also kind of hard to tell with the stacktrace. 

**How to reproduce**
- Moving towards the edge of the explored world always causes the game to crash. Conveniently, the last time it crashed it managed to save the exact location of the boat I was on, and the boat is still there, so circling it once pretty much guarantees reproducing the issue.

**Additional information**
Log with OptiFine: 
[crash-2020-07-26_22.38.11-server.txt](https://github.com/TerraForged/TerraForged/files/4979727/crash-2020-07-26_22.38.11-server.txt)
Log without OptiFine
[crash-2020-07-26_23.10.43-server.txt](https://github.com/TerraForged/TerraForged/files/4979744/crash-2020-07-26_23.10.43-server.txt)

**Comment by dags-** [comment]
Your village distance setting is set to 0. I suggest you stick to configuring the settings in the ui as it prevents mistakes like this

**Comment by JCLaHoot** [comment]
Thanks :) this worked. Not sure how village distance got to 0 though since it wasn't the case on world gen.
