### ISSUE TITLE
Terrain generation bug causes flatlands to appear

### ISSUE THREAD

**Issue by djmrFunnyMan** [TerraForged/TerraForged#236]
I created a new world messign with the settings to see what results will i get and i noticed gigant diorite flatlands cuttign trough the world
![2020-07-28_00 28 31](https://user-images.githubusercontent.com/68905776/88662026-aef51780-d0d9-11ea-8a2f-6ed9c3288183.png)
![2020-07-28_00 28 38](https://user-images.githubusercontent.com/68905776/88662034-b1577180-d0d9-11ea-9ef4-58e5dabe0390.png)
![2020-07-28_00 29 13](https://user-images.githubusercontent.com/68905776/88662038-b2889e80-d0d9-11ea-8874-a373c5ff5f73.png)
![2020-07-28_00 29 41](https://user-images.githubusercontent.com/68905776/88662046-b4526200-d0d9-11ea-8be6-eaa7741f80aa.png)

How to reproduce:
The only way to reproduce the bug is to use the same world gen settings i used and i won't type everything i changed here so here's the world
https://mega.nz/file/YvQClIDB#d-JvtpXDNoO2Qt-m88fVezufXiozmfsCyT6GQ8Y-DH4

**Comment by dags-** [comment]
Probably the continent size. Generally speaking; setting sliders to the extreme may break world-gen or cause weird problems
