### ISSUE TITLE
Snowy Tundra littered with trees

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#238]
**Description**
Last time I checked a Snowy Tundra wasn't full of trees but a treeless arctic region with very low vegetation like grass.
It looks like the `snowy_tundra` has the same decoration settings as a `snowy_taiga` as the two seamlessly transition into one another.

**How to reproduce**

1. Commence the following command `/terra locate biome minecraft:snowy_tundra`

2. Observe your surroundings

**Additional information**
![2020-07-29_10 55 51](https://user-images.githubusercontent.com/19509275/88779978-a3adf480-d18a-11ea-854e-924596695472.png)

**Comment by yurisuika** [comment]
Radius is set to 10; that is normal forest density. I use a radius of 30 for the tundra, try that.
https://github.com/TerraForged/TerraForged/blob/master/src/main/resources/data/terraforged/features/trees/spruce_tundra.json

**Comment by dags-** [comment]
@Quizer9O8 You need to cool it with the snide comments. The opening line is wholey unnecessary for the issue at hand. The second would have sufficed - clearly just a configuration error, thanks for reporting

**Comment by Quizer9O8** [comment]
@dags Well sorry about the first part, It was meant as a inside joke. I didn't mean to be snide or downright negative.
