### ISSUE TITLE
Rivers getting crammed up on continents

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#239]
**Description**
I noticed that on some smaller continents rivers tend to cluster around each other which can create strange formations shown in Additional information. Perhaps this can be solved by creating a system that checks if the starting point of main/branch rivers are too close to another river by simply canceling out one of the rivers or shorten the starting point of the river itself. 

As alternative rivers could make use of the distance/separation system that's in place for structures to make this occurrence less likely to happen.

**How to reproduce**

1. Generate a seed where you start on a small continent or with two small continents very close to each other
2. locate rivers within a close proximity to each other

**Additional information**
![afbeelding](https://user-images.githubusercontent.com/19509275/88828130-0f17b680-d1cb-11ea-8502-c71d5d9039af.png)

**Comment by dags-** [comment]
Currently forks check that they don't interesect another river, but obviously that doesn't prevent rivers starting very close to another.

The simplest solution would be to shorten the length of the fork slightly after confirming that it doesn't intersect another river. Very doable
