### ISSUE TITLE
Increase the structure distance slider limits

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#240]
**Please describe the feature you'd like to see:**
Whenever you scale up the continent size you won't be able to scale the distance and separation in chunks accordingly.
The distance and separation of structures in chunks is already an existing feature but this my proposal to improve further on it.

**What considerations for gameplay/performance/user-experience should be made:**
Increase the maximum/minimum cap of distance and separation in chunks.

**What alternatives or examples have you considered:**
As an alternative the distance and separation of structures in chunks could increase in size automatically if a feature like 'Automatic spacing' would be implemented. This feature will space out the structures automatically based on the continent scale.

**Comment by dags-** [comment]
I don't see what the relationship is between continent size and structure separation? Could you explain more why this would be useful?

**Comment by Quizer9O8** [comment]
If you increase your continent size, and biome size to higher numbers things will start to get massive. Massive landmasses, massive biomes which can cover thousand of chunks. if you wish to increase the structure separation size you'll soon hit the max cap of 200 chunks which means if you got one massive plains you will most likely finding over 25 villages in one biome. That's not ideal setting I would be honestly looking for.

So to balance that out we need either an increase of the structure size max cap to compensate for this or look for another alternative. As for the other alternative I put down earlier I realized making structure size scale to a reasonable amount depending on the continent size wouldn't really work out well without scaling the biome size as well. Otherwise some structures will become so rare you might have to go 3 continents far to find that certain structure. Just like how some of the sliders in TerraForged are linked to each other to prevent user errors while tweaking the coast, beach, shallow and deep oceans maybe having some kind of safegaurd (optional of course) might benefit the end-user.

**Comment by dags-** [comment]
I can increase the cap for sure. In the case of the structure settings it's there simply because a slider input has to have an upper and lower bound.

The distance and separation sliders deal purely with the spacing of instances of a structure. Restricting the number of occurances of that structure in any one biome cell is an entirely arbitrary constraint.

**Comment by Quizer9O8** [comment]
I think the cap increase would somewhat solve the continent/biome size issue.
