### ISSUE TITLE
TerraForged modifying tree density of biomes?

### ISSUE THREAD

**Issue by gamax92** [TerraForged/TerraForged#243]
**Description**
I've noticed that TerraForged might be modifying the density of trees in biomes of 'Oh The Biomes You'll Go'
The attached screenshots show a biome called 'Baobab Savanna' (byg:baobabsavanna) where tree placement is more/less dense than the biome should be. ~~I've had times where this same biome was so packed that there was almost no light under the trees.~~

**How to reproduce**
Forge 31.2.33
Minecraft 1.15.2
TerraForged-1.15.2-0.1.1
byg-1.0.10

Helper mods:
locatebiome-1.15.2-v1.0 (to easily find biome)
Xaeros_Minimap_20.17.0_Forge_1.15.2 (for pictures)
XaerosWorldMap_1.7.4_Forge_1.15.2 (for pictures)

Created world with JustAddBiomes preset
Ran `/locatebiome byg:baobabsavanna` command

**Additional information**
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
https://www.curseforge.com/minecraft/mc-mods/locatebiome
Baobab Savanna in TerraForged
![2020-07-30_23 06 06](https://user-images.githubusercontent.com/815145/89002289-ecb09680-d2b9-11ea-9060-c9068333ab7c.png)
Baobab Savanna in Buffet
![2020-07-30_23 09 16](https://user-images.githubusercontent.com/815145/89002373-1a95db00-d2ba-11ea-9522-81155e3a1188.png)

**Comment by dags-** [comment]
Note to self:
https://github.com/TerraForged/TerraForged/blob/master/src/main/resources/data/terraforged/features/trees/acacia.json

**Comment by gamax92** [comment]
I'm not sure if terraforged's custom trees apply here, byg adds in it's own log and leaf types, these are `byg:baobab_leaves` and `byg:baobab_log`
https://user-images.githubusercontent.com/815145/89008184-774bc280-d2c7-11ea-8349-101ca939043e.png
I got an example of some of the way more denser generations of this biome

**Comment by gamax92** [comment]
... I apologize for the false report, apparently I have two different versions of byg. One of which from curseforge that has the massive amount of trees, and one with the same filename but different size that is probably a git build and has different generation for this biome.

The two pictures are from the same git build, so there is still an odd tree density at times, but it is not as bad as the very dense picture that I reported before, so I'll remove that from this issue report.

**Comment by dags-** [comment]
Oh. Well looks like that biome does use acacia trees so TF probably replaces those which is probably fine:
https://github.com/TerraForged/TerraForged/blob/master/src/main/resources/data/terraforged/features/trees/acacia.json

If TF isn't replacing the mod trees then there's no other way that it'd be changing density of them.

**Comment by gamax92** [comment]
But the pictures clearly show that the density of them does change with terraforged compared to vanilla, those are from the same mod build.

**Comment by dags-** [comment]
Maybe that tree type places conditionally based on the acacia trees in that biome, or based on the terrain height or something - I've no idea, I don't write that mod.

The acacia trees are the only thing that TF would be replacing here. You can disable that by turning off TF's 'custom features' if you want.
