### ISSUE TITLE
Cave Generation under Villages

### ISSUE THREAD

**Issue by Cirone98** [TerraForged/TerraForged#245]
Good evening dags,

There is a problem generating caves under villages using version 0.1.1 of terraforged.  I have been able to reproduce this chunk error on many worlds with just terraforged installed and many more with other mods such as worley's caves to attempt to overwrite the cave generation.  The first picture shows the error underground while the second picture shows the surface from the same point of view and x-z coordinates.  I have not reproduced this error under any structure other than villages, though it might occur under them as well, but it is consistent that every village will consist of solid rock underneath with these hard edges through caves.  In vanilla Minecraft and with any other combinations of mods this error does not exist.  These edges trace a large box around the village (normally much larger than the villages appears on the surface).  I know terraforged claims to not affect caves since other mods have already improved them, but since it seems to be terraforged causing the error I hope you can replicate it and find a solution.

Thanks!

P.S. I've been following the mod since 0.0.1 and it blows me away every time a generate a new world.  Can't imagine playing MC without it any more.

Underground:
![2020-08-01_17 51 13](https://user-images.githubusercontent.com/62605415/89111135-1257b000-d420-11ea-9697-08efb61c26a4.png)

Surface:
![2020-08-01_17 54 13](https://user-images.githubusercontent.com/62605415/89111140-21d6f900-d420-11ea-8eb9-7de8eba26765.png)

**Comment by dags-** [comment]
It's an attempt to prevent caves from digging out the ground underneath villages. It currently does this at chunk resolution which is probably a bit too blunt a method. I'll see if I can simply prevent the caves from breaching the surface of chunks that contain a village rather than blocking entirely. Failing that I'll add a toggle setting for the current behaviour

**Comment by Cirone98** [comment]
I think a toggle would work very well.  I have actually already setup the caves to not reach the surface using worley's caves and have removed ravines with the cave manager mod linked in the discord.  This issue is much less noticeable without a cave mod installed since the caves are generally smaller in size and it would look more like a dead end.  So for the people using cave mods that exacerbate the issue, I would be happy to share my configs to prevent surface breaches with anyone who wanted them.

**Comment by dags-** [comment]
It turned out to be fairly simple to just have them stop a few blocks below the surface if the chunk has surface structures

**Comment by Cirone98** [comment]
Perfect
