### ISSUE TITLE
Terrain is not loaded

### ISSUE THREAD

**Issue by John-Deere89** [TerraForged/TerraForged#246]
As you can hardly see, the map is no longer loaded
Why?
i can't answer it

![2020-08-02_17 42 40](https://user-images.githubusercontent.com/63151473/89126646-9d4fad80-d4e7-11ea-8e06-9035bc97101c.png)

**Comment by CreativeRealms** [comment]
Journeymap and Optifine do not work together very well right now and cause lots of chunk issues. Remove one of them and it will fix it.

**Comment by John-Deere89** [comment]
how about the voxelmap is the more compatible compatible?

**Comment by dags-** [comment]
If it's journeymap that you remove then you'll also need to make sure that your optifine render distance is 32 or lower (33 and above doesn't work correctly when running optifine with forge)

**Comment by CreativeRealms** [comment]
Voxelmap seems to work fine.

**Comment by John-Deere89** [comment]
thanks for the information
