### ISSUE TITLE
Block Layering Compatibility

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#248]
**Please describe the feature you'd like to see:**
[Block Layering](https://www.curseforge.com/minecraft/mc-mods/block-layers) adds layers which are similar to snow as surface/ground blocks like grass, dirt gravel and (red) sand.  Having these spawn in naturally in the terrain would make things a lot more smoother.

**What considerations for gameplay/performance/user-experience should be made:**
I do not know what systems are in place to generate smooth snow layers in TerraForged terrain but maybe the very same system can be used to create smooth layers for grass, dirt gravel and (red) sand.

**What alternatives or examples have you considered:**
None.

**Comment by CreativeRealms** [comment]
This won't happen because TerraForged will only ever have vanilla blocks. However, it might be a possibility that it can detect layers from other mods to use in the world gen via a config file or something (I want it to work with CR like this).

**Comment by Quizer9O8** [comment]
I basically want this to be an option to turn on/off layers via a config file as well. This is not needed as a default setting in TF but rather optional.

**Comment by CreativeRealms** [comment]
That's already a thing. Smooth snow in one of the last pages in settings.

**Comment by Quizer9O8** [comment]
I'm aware of that. But not for mods that add their own custom layers.

**Comment by dags-** [comment]
TerraForged has an event api for this
