### ISSUE TITLE
Description not visible in preset via normal means

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#249]
**Description**
Placing a description on your preset won't show in the menu to choose presets from if placed in `.minecraft/mods/config/terraforged/presets`. Only presets that are directly placed in the TerraForged `.jar` file will have their description visible.

**How to reproduce**
_Preset with no description visible_
1. Create a preset with a description
2. Place the preset in `.minecraft/config/terraforged/presets`
3. Refresh the TerraForged customization screen and hover over your preset, you won't see the description you placed inside your preset

_Preset with description visible_
1. Create a preset with a description
2. Place the preset in `.minecraft/mods/TerraForged-1.15.2-0.1.2.jar/presets`
3. Refresh the TerraForged customization screen and hover over your preset, you will see the description you placed inside your preset

**Additional information**
None.

**Comment by dags-** [comment]
It's for built-in presets only
