### ISSUE TITLE
Having more clarifcation what's being searched for when using /terra locate (biome, terrain or both)

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#250]
**Please describe the feature you'd like to see:**
Having more clarification what's currently being searched for when using `/terra locate` would make things a lot more easier to look back at rather than guessing what your last 3 specific searches were:
![afbeelding](https://user-images.githubusercontent.com/19509275/89457512-cb422580-d765-11ea-93a8-8fb459a65cf1.png)

**On another related note:**
When a nearest match is found I noticed that there's still a `~` left when displayed. I dont know if this is intentional but shouldn't it show the right Y: level you're about to get teleported to since the bug that caused you to spawn inside the terrain got fixed a long time?

**What considerations for gameplay/performance/user-experience should be made:**
Instead of only showing _**Searching...**_ and _**Nearest match:**_ Have both these messages show the biome and or terrain you're looking for straight away. It should be like this: _**Searching minecraft:plains badlands**..._ and _**Nearest match minecraft:plains badlands**:_

**What alternatives or examples have you considered:**
None.

**Comment by earomc** [comment]
Rejected without a discussion on why you don't want to add it? @dags- Seems weird to me...

**Comment by dags-** [comment]
I have no plans to add this.
Command history is a thing.
Follow the issue guidelines re: be concise.
PRs are also a thing.
