### ISSUE TITLE
Crash on Worldgen with Worley's Caves

### ISSUE THREAD

**Issue by Divineaspect** [TerraForged/TerraForged#252]
**Description**
Crash on Worldgen with Worley's Caves

**How to reproduce**
Using the ATLauncher for a custom pack.

**Additional information**
https://pastebin.com/YDWhPkJW

**Comment by Divineaspect** [comment]
https://github.com/superfluke/WorleyCaves/issues/32

**Comment by dags-** [comment]
I'd suggest you find the log that corresponds with the crash and look back in it for any errors that other mods might be throwing. My guess would be that one is throwing an error that is somehow preventing WC from initializing it's cave carver
