### ISSUE TITLE
[Technical Proposal] Terrain Registry via Forge

### ISSUE THREAD

**Issue by aeroeng15** [TerraForged/TerraForged#253]
**Please describe the feature you'd like to see:**
- Proper registry system for terrains using `ForgeRegistries`

**What considerations for gameplay/performance/user-experience should be made:**
- Single instance of terrains, into which settings are fed
- Allows for mods to supply additional terrains (some engine mechanics would have to think about how to utilize terrains generically)
- World gen settings screen allows for dynamic population of terrains (i.e. only terrains that need the `TerrainSettings` would populate)

**What alternatives or examples have you considered:**
- Custom registry in Forge to mimic how `Biome`'s are accessed/registered
- Currently working through some initial implementation details in forks (this is _somewhat_ breaking the paradigm already set)
    - May need to think of `Terrain`'s as grouped by `TerrainType`

**Comment by dags-** [comment]
There is an API for this already. Registries add nothing useful
