### ISSUE TITLE
Error loading the world

### ISSUE THREAD

**Issue by John-Deere89** [TerraForged/TerraForged#255]
We have been playing on the card for a while now, we are further out and now the card is no longer loading properly
Can't the world be too unde?
What's this?

![2020-08-09_15 31 35](https://user-images.githubusercontent.com/63151473/89733466-f8d4ea80-da55-11ea-87e1-fb7f7229d886.png)
![2020-08-09_15 33 34](https://user-images.githubusercontent.com/63151473/89733467-fa061780-da55-11ea-8bb1-a14d6b15811b.png)

**Comment by dags-** [comment]
Can you recreate without optifine installed?

**Comment by John-Deere89** [comment]
your mod won't bring me anything without optifine :)
if it's because of that

**Comment by dags-** [comment]
Optifine has a bug that breaks chunk loading when you set your render distance over 32. It may break things in other situations too.
It's nothing to do with TF.

**Comment by John-Deere89** [comment]
my setting is 16 distance and only occurs in connection with your mod

**Comment by dags-** [comment]
If you can demonstrate that it's an issue without Optifine installed then I've got something to look into.

If you don't want to do that, then just remove TerraForged

**Comment by John-Deere89** [comment]
![2020-08-09_16 29 42](https://user-images.githubusercontent.com/63151473/89734635-997ad880-da5d-11ea-80a0-ec8e3466d152.png)
please a world without Optifine with your mod

**Comment by dags-** [comment]
Please open a new issue using the bug report template and fill in with as much information as possible.  Provide your logs, modlist etc.

Thanks
