### ISSUE TITLE
Loading problems of the worlds

### ISSUE THREAD

**Issue by John-Deere89** [TerraForged/TerraForged#256]
I've now tested your mod does not work with maps mods like voxelmap ect
you should fix that
I've now flown back and forth in the world for a while without voxelmod then ran and loads everything
please fix that one quickly

**Comment by dags-** [comment]
Please use the issue template and provide sufficient information:

```
**Description**
Please describe the problem clearly and concisely

**How to reproduce**
- Describe your setup if using anything other than the Mojang launcher or standard forge server
- List any third-party mods (& their version number) that may be relevant to the issue
- Provide a simple step-by-step guide to recreate the problem

**Additional information**
Add screenshots, world-seeds, co-ordinates, log files, links to conflicting mods

```

**Comment by John-Deere89** [comment]
mod louder Forge
Mod TerraForged & Voxelmap

[launcher_log.txt](https://github.com/TerraForged/TerraForged/files/5047900/launcher_log.txt)

I do not know more or can not serve with more have just taken another map mod it did not even run 3m

**Comment by dags-** [comment]
Ok so you're running with many mods.... One of the ones that adds structures or world-gen features is probably freezing the chunk generator causing the chunks to stop loading. You'd need to go through and test with and without each one.

Again, if you can demonstrate the issue with _just_ TerraForged then let me know.
