### ISSUE TITLE
Birch Generation Height Check

### ISSUE THREAD

**Issue by Tartrus1** [TerraForged/TerraForged#257]
**Description**

Using terraforged 0.1.1

Testing out Ilmango's universal tree farm (1.15) with terraforged trees and birch, oak, and jungle trees do not grow.
Using birch trees I tested if the 5x5 area is large enough and they will grow. Removed all blocks above sapling and the birch tree grew right away. Tested height by placing blocks above the sapling and even 30 blocks above, the birch sapling would not grow unless the block was broken. Oak and jungle was not tested but issue may be the same.

**How to reproduce**
Using Ilmago`s tree farm: https://www.youtube.com/watch?v=Kw3kgq19nrU world download in description, changed to terraforged world in NBT editor to test tree gen.

Included new world with tree farm and generator name changed to terraforged:

[1_15utf ilmango.zip](https://github.com/TerraForged/TerraForged/files/5054551/1_15utf.ilmango.zip)

Remove flying machine component above growing chamber and all blocks above sapling. Successively place blocks higher to test tree height.

**Comment by dags-** [comment]
TF trees need direct light overhead for the sapling to grow

You can disable TF's custom trees in the world gen settings ('custom biome features' I think)

**Comment by Tartrus1** [comment]
Ahhh thank you, that makes sense! Unfortunately, or fortunately in your case, I like the terraforged trees too much to part with them. Farm seems to work with spruce and acacia at least!

**Comment by wa4-fearless-otter** [comment]
Shouldn't tree growing follow the default behaviour, that blocks can be above a sapling?
