### ISSUE TITLE
Lost Cities compat

### ISSUE THREAD

**Issue by strivenous** [TerraForged/TerraForged#259]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
When my TerraForged world was made in SP, it also had a Lost Cities compatibility. When it was moved to MP Forge server-side, terrain gen was identical, but the cities were missing (as in the weren't just there, the terrain was fine however).

**How to reproduce**
Make world with Lost Cities integration in SP.
Move to MP with level-type terraforged (is it supposed to be this one?)
Pre gen.

**Additional information**
No crashes, modlist is:
AI-Improvements-1.15.2-0.3.0.jar
BetterCaves-1.15.2-1.0.jar
BetterMineshaftsForge-1.15.2-1.3.jar
Dynmap-3.0.1-forge-1.15.2.jar
FastLeafDecay-v22.jar
incontrol-1.15-4.0.4.jar
logprot-1.15.1-1.2.jar
lostcities-1.15-3.0.1-alpha.jar
MixinBootstrap-1.0.3.jar
modlist.txt
NetherPortalFix_1.15.2-6.0.2.jar
performant-1.15-3.8m.jar
PreGenForge-0.1.1-mc1.15.2.jar
TerraForged-1.15.2-0.1.2.jar
AI-Improvements-1.15.2-0.3.0.jar
BetterCaves-1.15.2-1.0.jar
BetterMineshaftsForge-1.15.2-1.3.jar
Dynmap-3.0.1-forge-1.15.2.jar
FastLeafDecay-v22.jar
incontrol-1.15-4.0.4.jar
logprot-1.15.1-1.2.jar
lostcities-1.15-3.0.1-alpha.jar
MixinBootstrap-1.0.3.jar
modlist.txt
NetherPortalFix_1.15.2-6.0.2.jar
performant-1.15-3.8m.jar
PreGenForge-0.1.1-mc1.15.2.jar
TerraForged-1.15.2-0.1.2.jar

**Comment by dags-** [comment]
I don't know how that mod is supposed to be configured to run on the server.
Maybe create the world in SP and transfer that.
