### ISSUE TITLE
All Plains

### ISSUE THREAD

**Issue by EchoRanger** [TerraForged/TerraForged#260]
**Description**
Fresh from the download, 1.15.2, it's all plains and ocean. No matter how I change the weights it only spawns me in plains and no matter how far I travel it's all plains. No mountains, mesa, jungle, desert, anything.

**How to reproduce**
Plug and play. 

Has this happened before? Any idea how I can get the weights to respond meaningfully, and get rid of these darn plains?

**Comment by dags-** [comment]
Clear your terraforged config folder and try again with default settings
