### ISSUE TITLE
Badlands spawning

### ISSUE THREAD

**Issue by Martholomeus** [TerraForged/TerraForged#264]
Attempting to create an all-desert world, instead only "badlands" are spawning. Is this a bug or am I missing something?

Creating a new map: https://imgur.com/dCjkvav

Badlands sliders set all the way down to ZERO weight. According to the biome peview map on the right, none of the biomes are going to be badlands: https://imgur.com/CxKe15X

After spawning, everything is Badlands & wooded badlands. Not a single desert in sight: https://imgur.com/6hQNimW

**Comment by dags-** [comment]
Hi. Badlands are a type of desert. You'll find that your isalnd is a mix of large areas of yellow deserts and badlands - the grouping of which is controlled by the 'macro noise' slider. You might be able to use the biome_weights config to reduce the amount of badland biomes.
