### ISSUE TITLE
compatibility mod valhesia structures

### ISSUE THREAD

**Issue by mouchas29** [TerraForged/TerraForged#266]
hello, sorry for the mistakes i'm french don't speak english well so i used google translate. My problem is the following one I installed terraforged in 1.15.2 and the valhesia structures mod which adds many structures to the game. However when I run the game with the terraforged generation no problem but when I go to do a / locate structure of valhesia, it is impossible to find these last, do you know if there is an incompatibility between the two mods?

**Comment by dags-** [comment]
Nope they all seem to work fine. Some structures may spawn far away which can make the locate command take a long time or fail
