### ISSUE TITLE
Is there an ETA for 1.16.2 release

### ISSUE THREAD

**Issue by djmrFunnyMan** [TerraForged/TerraForged#267]
The mod is said to upgrade to ver 1.16.2 but it's been 2 weeks since that version release and still no word about when will we be getting the updated version

**Comment by earomc** [comment]
As a programmer you can NEVER tell when exactly youre finished. You just have to wait. It isn't that hard.

**Comment by Quizer9O8** [comment]
Instead of asking for an ETA you can also be productive by suggesting features for the next update.
