### ISSUE TITLE
Inaccurate biome lookups on ungenerated or unloaded terrain

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#27]
**Description**
For some unclear reason weird cut off biome borders start to appear after using PreGenForge and JourneyMap for automapping. Going into them these causes them to disappear on the map.

**How to reproduce**

1.  Install **TerraForged, PreGenForge** and **Journeymap**.

2. Start up **Minecraft Launcher** Go to **Settings** and enable **Open output log while games are running** (you'll need this later on), go back to **Minecraft: Java Edition** and launch the game. Once in the main menu go to **Options**, **Video Settings** and crank up **Render Distance:** to **32 chunks**.

3. Exit  **Options**, go to **Singleplayer**, **Create a new world**, change **Gamemode:** to **Creative**, go to **More Options**, turn **Generate structures:** to **Off** and change the **World Type:** to **TerraForged**.

4. **Create a new world** and use the following commands in sequence: `/gamerule doDaylightCycle false`, `/gamerule doWeatherCycle false`, `/gamerule doMobSpawning false`, `/gamerule randomTickSpeed -1`, `/kill @e[type=!minecraft:player]` (do this twice), `/pregen start 0 0 50` (the **Minecraft game output** will tell you how far PreGen currently is).

5.  Once **PreGenForge** is done open in **JourneyMap** the **Fullscreen Map**, go to **Options**, open up **Cartography**, and disable the following features: **Blend Foliage, Blend Grass, Blend Water, Show Bathymetry, Show Crops, Show Plants**. Select the following features: **Reveal Shape : Square, Render Delay : 0, Cave Max Distance : 32, Surface Max Distance : 32**. Close **Options** click on **Auto-Map** and map all regions. 

6. Once automapping is done you'll see straight looking phantom biomes on the map like this Dark Forest here:

![afbeelding](https://user-images.githubusercontent.com/19509275/76147264-c8e67d00-609a-11ea-9b3e-1155455e3922.png)

**Additional information**
This issue is known by the JourneyMap team: https://github.com/TeamJM/journeymap/issues/185

**Comment by mysticdrew** [comment]
Journeymap Dev here. 

Seems that getting the biomes and their associated blockcolors is not very accurate for unloaded chunks for worlds that have the terraforged word type. I am still doing some investigating on what is causing the issue exactly. 

I will update as I found out more.

**Comment by dags-** [comment]
Could well be my biome provider. Updating from 1.14 to 1.15 has been a bit funky for biomes

**Comment by dags-** [comment]
So my biome provider works based on block coord inputs which works just fine during my own chunk generation, but the rest of minecraft uses 'biome coordinates' with it (ie `blockX >> 2, blockZ >> 2`) which would explain why the world provides wholly inarccurate results for ungenerated chunks

**Comment by mysticdrew** [comment]
I pulled your latest changes and built TerraForged which had some issues I had to address so it would build. 

I also improved how I get my biomes. The 1.15 biome changes are kind of annoying to be honest. 

I feel we are pretty close here, however there is some biome bleeding happening still when getting block colors for unloaded chunks. When traveling where biomes connect and loading the chunks the map corrects itself. 

When I say biome bleeding, it was a savanna biome went about a 3/4 of a chunk into a jungle biome, so on the map the jungle trees were savanna yellow. When I would do a biome check on those blocks it was saying savanna but when I would move to it, and load the chunks I would get the correct results. 

I can get some screenshots later today for you. 

By the way, this mod is super cool. When I have time to play minecraft and set up a server, I will definitely be using it. The world gen is better than anything I have ever seen before, great work!

**Comment by dags-** [comment]
Ah, my lacking documentation strikes again! To build you need to use the `publish` task to prevent ForgeGradle reobf'ing the module dependencies before the 'main' module

Can confirm I've been having trouble getting my biome look-ups to match perfectly with what actually gets generated but it seems to be close-ish. I'll be continuing to try improve the results this week as I'm currently relying on some magic numbers to offset coordinates which I don't like one bit XD

Appreciate it :) & likewise, JM's such a cool mod!

**Comment by dags-** [comment]
I've found and fixed another bug that was contributing to this problem. The biome lookup should now be correct to within about 4 blocks, possibly with some variance from the biome magnifier function

**Comment by mysticdrew** [comment]
The bug may have been exacerbated 
0.0.2 
![image](https://user-images.githubusercontent.com/5459941/76319098-b2b00b00-62ac-11ea-8978-5109dabedc5f.png)

same location in 0.0.3

![image](https://user-images.githubusercontent.com/5459941/76319516-5699b680-62ad-11ea-9144-bfca77813bad.png)

**Comment by dags-** [comment]
I can't fix the offset issue in 0.0.2 worlds whilst maintaining seamless chunk transitions for new chunks. These worlds will continue to generate offset from the biome lookup, and - now I've removed the magic offsets from my BiomeProvider - the problem looks worse.

If you create that seed anew under 0.0.3, things should hopefully line up much better (hopefully!)

**Comment by mysticdrew** [comment]
Good call! I should have tested it initially with a new world. 

So far with my new world, things are looking pretty accurate.

**Comment by mysticdrew** [comment]
I've done a bit more testing and it seems to be resolved!

**Comment by dags-** [comment]
Nice, I think the remaining inaccuracy will be down to me not using the same fuzzing technique during gen that the client uses to warp biome edges, but I can live with that for now.

Thanks for the input!
