### ISSUE TITLE
Infinite Loading generator settings from level.dat

### ISSUE THREAD

**Issue by DevonX** [TerraForged/TerraForged#270]
Hi. i am running the Terraforged mod(0.0.15) on the Vallhelsia 2 pack (2.2.9) on a server and i am having some issues with Loading generator settings from level.dat that reapeats infinitely. This is causing the server to chug and is spamming the console log. i can manage to get on to the server but the performance is quite bad. 

Reproduced by:
- Running Valhelsia 2 pack() on a server with the Terraforged mod.

https://i.imgur.com/AZfwqVt.png

**Comment by DevonX** [comment]
Same issue with the latest version on the mod in the pack. new text but it is still looping 
![logspam2](https://user-images.githubusercontent.com/1227739/93017725-3daaee80-f5cb-11ea-985b-d866abc4dd7b.png)

**Comment by DevonX** [comment]
Update. it seems to be crashing now too. Here is the latest crashlog https://gist.githubusercontent.com/DevonX/d2f12fbc24bf80b6bd423e77003944e8/raw/a696f6649f49f3dc5144718b4b20b47fa0b820d1/gistfile1.txt

**Comment by dags-** [comment]
Seems like something in the modpack is erroring during loading of the datapacks.

You'd need to take up with the curators of the modpack you're using. If they can narrow it down to being TF then feel free to relay their findings here.

**Comment by dags-** [comment]
I'd add that the following line from your crash looks concerning:
```
at cjminecraft.doubleslabs.api.ServerWorldWrapper.<init>(ServerWorldWrapper.java:65)
```

I'd look there first, personally. Might be nothing though

**Comment by dags-** [comment]
Just to confirm, this is a problem with the double slabs mod which for some reason is trying to create a new ServerWorld instance whilst saving/loading its TileEntities...  o_o
