### ISSUE TITLE
Steppe and Cold steppe biomes weather aren't working.

### ISSUE THREAD

**Issue by augustolobo18** [TerraForged/TerraForged#271]
Basically, I built my house in the terraforged:steppe biome and when it starts raining, there's no sound of rain. When I go to the minecraft:plains biome there's normal sound of raining, but when I go to terraforged:steppe there's no sound. But you see rain, the rain falls but there's no sound. I actually discovered that the game doesn't recognize that it's raining at all.

I'm using with Optifine and the Serene Seasons mod, and when I turns into winter, the snow particles fall from the sky but snow doesn't pile up, as it does in all other biomes. But what is more stressful is that steppe isn't like desert or mesa, where it just doesn't rain. It rains, there's rain and snow particles, but no sound of rain and no snow piling up. 

Also, but I don't if this is an Terraforged issue or a Serene Seasons issue, but rivers also didn't froze, even in winter there was rain particles falling. But in rivers there was rain sound. 

I think Terraforged with Serene Seasons is an awesome combo, I think both mods should work together properly. 

PS: There's no sound of rain even without any other mods.

**Comment by dags-** [comment]
I think it's just because steppe's rain strength is very low so mc doesn't play a sound for it
