### ISSUE TITLE
Possibility to implement: Base "length" slider for Mountain Chains

### ISSUE THREAD

**Issue by AngusKeane** [TerraForged/TerraForged#272]
**Feature requests should adhere to the following guidlines:**
- be concise & describe in high-level terms (ie "please add a sand dunes biome, here's a picture")
- technical proposals or system overhauls should be demonstrated in a working fork/pull-request
- please do not solicit with the promise of donations and such

**Please describe the feature you'd like to see:**
Implementaion of some form of slider for: Base "length" slider for Mountain Chains, Allowing for single mountain chains or longer, or some Bias method
**What considerations for gameplay/performance/user-experience should be made:**
Possibly allow for players to increase chance of single "mountain" or much longer (tiers) for their world. 
**What alternatives or examples have you considered:**
No obvious alternatives but examples could include:

HOME TOWN MOUNTAIN & TIERS 
![image](https://user-images.githubusercontent.com/65269816/93197852-87dccd00-f78f-11ea-895a-6ba88aa042cd.png)
![image](https://user-images.githubusercontent.com/65269816/93198087-d9855780-f78f-11ea-850e-9f32fece979d.png)

Thank you for the amazing mod <3 -

**Comment by dags-** [comment]
Both chains and individual mountains occur in the generator as-is.

There's not really a single parameter that can control it. A lot of it is down to the way different worldgen components interact together - when you start restricting those to get more repeatable/predictable results elsewhere you take a lot of variation out of the generator as whole

**Comment by AngusKeane** [comment]
Ah yes thank you , for clearing it up 😍
