### ISSUE TITLE
[1.15.2] Not a only server-side mod

### ISSUE THREAD

**Issue by Intezium** [TerraForged/TerraForged#274]
Forge-31.2.41
TerraForged-0.1.2
This prevent joining the server.
![](https://user-images.githubusercontent.com/20191322/94384652-c8ebbe80-014b-11eb-967c-4388b17f0691.png)

**Comment by dags-** [comment]
It's Forge that isn't letting you connect. You either need to remove Forge from your client or install TF on your client
