### ISSUE TITLE
Mod uses BoP Alps incorrectly

### ISSUE THREAD

**Issue by quarlessam** [TerraForged/TerraForged#275]
**Description**
I downloaded this and BoP and used the preinstalled JustAddBiomes preset. I was exploring around and found an alps biome with low, very flat terrain along a river instead of the very high terrain you'd expect.

**How to reproduce**
- Set preset to JustAddBiomes
- (Set world spawn to Origin)
- Set seed to -173752679
- Teleport to 366, 69, -2881

**Additional information**
<img width="1440" alt="Screen Shot 2020-09-30 at 2 47 15 PM" src="https://user-images.githubusercontent.com/24835546/94726870-d9f32600-032b-11eb-8ff4-95737bcda838.png">

**Comment by dags-** [comment]
Rivers can cause terrain to flatten where it might have been taller otherwise
