### ISSUE TITLE
Terrain gen crashes when using terraforged and "Oh the biomes you go"

### ISSUE THREAD

**Issue by viveleroi** [TerraForged/TerraForged#276]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
1.15.2

Terraforged works fine with BoP, but when I instead use terraforged and "oh the biomes you go", terrain gen randomly stops and entire chunks are missing.

**How to reproduce**
- Custom twitch modpack
- Add terraforged, add oh the biomes you go
- Make a new single player world, choose "terraforged" as world type
- Explore. You'll eventually see missing chunks.

**Additional information**
N/A

**Comment by dags-** [comment]
I'm not able to reproduce and haven't had any other reports regarding byg.
Would need to see some logs to be able to help further

**Comment by zoyer2** [comment]
Tested it too, no crash after 10 min of soaring

**Comment by Calendis** [comment]
Do you happen to have JourneyMap and Optifine installed? @viveleroi
