### ISSUE TITLE
Bug in Terrain generation with modded stone

### ISSUE THREAD

**Issue by Mw119** [TerraForged/TerraForged#277]
When Forge stonetypes are disabled within their respected mod configs, TerraForged worlds will still generate with these stonetypes.

Tested using Create and Quark, both stones disabled within configs. Is this a bug or lack of mod integration I don't know.

Other related info: 
- Minecraft version 1.15.2
- Forge 31.2.45
- TerraForged 1.15.2-0.1.3
- Create 1.15.2_v0.2.4e
- Quark r2.1-245

**Comment by dags-** [comment]
TF uses these [block tags](https://github.com/TerraForged/TerraForged/wiki/Mod:-Tags:-Blocks) for the materials it places in the world. Other mods can choose to add their blocks to those tags to make TF use them in world-gen.

I'm not familiar with how those mods handle their configuration and if their configs change what blocks they add to the above tags. An option might be to make your own datapack with the block tags populated with only the blocks you want to see (using `"replace": true` to make it override any other entries to the tag(s) that other mods might have added).

You could use TF's default block tags as a starter, [found here].(https://github.com/TerraForged/TerraForged/tree/master/src/main/resources/data/forge/tags/blocks)
