### ISSUE TITLE
Can't launch game with mod installed

### ISSUE THREAD

**Issue by shepplin** [TerraForged/TerraForged#279]
I'm trying to play with this mod in a mod pack but Minecraft will not launch with this mod installed. I keep getting Exit Code: 0. I have 9GB of RAM dedicated with 16GB total and I'm running it on Minecraft 1.15.2 on Forge version 31.2.41. Any help or information of what I could be doing wrong would be greatly apreciated.

**Comment by dags-** [comment]
logs please

**Comment by shepplin** [comment]
> 
> 
> logs please

[latest.log](https://github.com/TerraForged/TerraForged/files/5344830/latest.log)

**Comment by dags-** [comment]
That shows nothing to do with terraforged, looks like your game installation is wrong. I'd try a clean install first and if that fails you'd need to seek help from forge
