### ISSUE TITLE
Global Temperature and Moisture settings

### ISSUE THREAD

**Issue by Agonizes** [TerraForged/TerraForged#28]
Hi, maybe this is already on the planning but would it be possible to create global temperature and moisture settings for the world generation? 
That would allow, for example, for the creation of very hot and dry worlds or very wet ones or cold worlds. 
Maybe the sliders could work in a way that shrinks or grows a climate's width on the world, where at zero a climate zone does not occur but at a hundred the climate zone covers the entire world.

I guess this result could also be reached with black/white listing individual minecraft biomes to only allow biomes of your choosing, but with global temperature and moisture sliders, it would be possible to have very wide bands of, for instance, deserts, and very thin bands of arctic terrain.

**Comment by dags-** [comment]
Hi, this was mentioned in curseforge comments & I must have forgotten to open a ticket for it. Yes, I'd like to expose settings for altering the temp/moisture ranges. This should give a degree of control over climate bands too.

**Comment by dags-** [comment]
Added to 0.0.8
