### ISSUE TITLE
Terraforged world crashing when using maps and opening doors

### ISSUE THREAD

**Issue by Pyrotekis** [TerraForged/TerraForged#280]
Created a new world and everything runs smoothly but whenever I try to use maps, open doors, etc

[crash-2020-10-08_14.08.49-server.txt](https://github.com/TerraForged/TerraForged/files/5350605/crash-2020-10-08_14.08.49-server.txt)
[crash-2020-10-08_14.10.37-server.txt](https://github.com/TerraForged/TerraForged/files/5350606/crash-2020-10-08_14.10.37-server.txt)
[crash-2020-10-08_14.05.55-server.txt](https://github.com/TerraForged/TerraForged/files/5350607/crash-2020-10-08_14.05.55-server.txt)

**Comment by dags-** [comment]
Your crash is unrelated to TerraForged
