### ISSUE TITLE
License Requirement

### ISSUE THREAD

**Issue by Somebody7850** [TerraForged/TerraForged#281]
**Description**
Whenever I start my Minecraft I get an error by Forge saying I am missing the license requirement in mod file.
![image](https://user-images.githubusercontent.com/72626722/95621545-e409d880-0a3f-11eb-9cea-c3606ca0e4f1.png)

**How to reproduce**
I am using the Java version of Minecraft with the latest Optifine and Forge installed.
All I did for this to happen was install the mod and put it into the mod folder.
![image](https://user-images.githubusercontent.com/72626722/95621356-8a091300-0a3f-11eb-99aa-ae6d50cc357a.png)

**Comment by dags-** [comment]
TerraForged isn't available for 1.16.3
