### ISSUE TITLE
TerraForged not generating correctly with BoP, the alps are almost completely flat, as are most of the BoP biomes.

### ISSUE THREAD

**Issue by TheRaptorMovies** [TerraForged/TerraForged#287]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
Please describe the problem clearly and concisely

**How to reproduce**
- Describe your setup if using anything other than the Mojang launcher or standard forge server
- List any third-party mods (& their version number) that may be relevant to the issue
- Provide a simple step-by-step guide to recreate the problem

**Additional information**
Add screenshots, world-seeds, co-ordinates, log files, links to conflicting mods

**Comment by dags-** [comment]
You just need to look around a bit more. It's not like vanilla gen where a given biome has the same terrain for every instance of it you find.

Also keep in mind that river networks & lakes will lower the terrain local to them creating valleys and plains (which is probably what is happening in the case of the alps biome you found).
