### ISSUE TITLE
[1.15.2] Wrymroost incompatibility leading to crash.

### ISSUE THREAD

**Issue by EightBlade** [TerraForged/TerraForged#290]
I can't seem to find any issues relating to this here.
**Description**
Whenever generating a world with Wrymroost installed I get a crash. Included is a crash log of just this.
https://pastebin.com/4gXgRD2K

**How to reproduce**
- List any third-party mods (& their version number) that may be relevant to the issue
Wyrmroost-1.15.2-1.2.5
https://www.curseforge.com/minecraft/mc-mods/wyrmroost

**Comment by Won-Ton** [comment]
Nothing to do with TF
