### ISSUE TITLE
Too many ocean monuments at predictable locations

### ISSUE THREAD

**Issue by gbl** [TerraForged/TerraForged#291]
_Please take a look through the [existing issues](https://github.com/TerraForged/TerraForged/issues) to see if your problem has already been reported and reply to that rather than creating a new thread :)_

**Description**
Terraforged seems to create lots of ocean monuments in an almost regular pattern; as if the monuments were placed on the corners of a square grid, then randomly shifted by a small amount. See the attached screenshot.

![Screenshot_2020-11-18_14-12-32](https://user-images.githubusercontent.com/243563/99535338-14cb1f00-29a9-11eb-8383-0f702026d72c.png)

**How to reproduce**
Using MultiMC, MC 1.15.2, Forge 31.2.0 , and this mod list. World was pregenerated using WorldPreGenerator.
```
DurabilityViewer-1.15.2-forge31.1.30-1.7.1.jar
Dynmap-3.1-beta4-forge-1.15.2.jar
forgemod_VoxelMap-1.9.28_for_1.15.2.jar
grid-1.15.2-forge31.1.0-1.6.jar
randomblockplacement-1.15.2-forge31.1.0-1.0.jar
TerraForged-1.15.2-0.1.2.jar
WorldPreGenerator-1.15.2-1.1.0.jar
```
DurabilityViewer, grid, and randomblockplacements are my own mods, neither of which affects world generation in any way.

As the terraforged world config seems to be saved in level.dat, I attached that file (zipped as GH doesn't allow me to upload .dat files directly). Please let me know if you need any other files.
[level.dat.zip](https://github.com/TerraForged/TerraForged/files/5560248/level.dat.zip)

**Comment by Won-Ton** [comment]
That is basically how structure placement works (it's a vanilla system, not TF's). There are sliders to change the grid spacing and offset in the generator settings if you want to change the scaling of the parameters.

Keep in mind that if you look at almost anything procedural from a far (or close) enough distance you'll see patterns from the underlying implementation. Minecraft & TF are designed around the in-game perspective
