### ISSUE TITLE
1.16.3 release

### ISSUE THREAD

**Issue by vinnyg0621** [TerraForged/TerraForged#292]
could we see this mod in 1.16? I really want to make my world really good-looking with all my mods I have for 1.16 :(

**Comment by vinnyg0621** [comment]
actually, 1.16.3 has a stable forge version now, so I think the mod should be updated

**Comment by Won-Ton** [comment]
Forge doesn't have proper support for worldgen modding just yet. There are a couple of PR's open that both plug the (main) gap as far as TF is concerned so when one of those is accepted it shouldn't be long for a beta version of TF to be put out.

For reference:
https://github.com/MinecraftForge/MinecraftForge/pull/7448
https://github.com/MinecraftForge/MinecraftForge/pull/7353

Rest assured we follow forge development closely (and try to help out where we can) so don't worry about giving us the go ahead to update...

Stuff takes time, please be patient.
It's not like 1.15.2 has suddenly stopped working ;)
