### ISSUE TITLE
Configurable biome maps

### ISSUE THREAD

**Issue by xynerorias** [TerraForged/TerraForged#293]
**Please describe the feature you'd like to see:**

It would be very nice to have control of what biomes are generated and where. You can already change the weights of biomes by listing their IDs and assigning them a value between 0 to 10, but it would be nice to change what biome spawns in what area, have control over the biome mapping. It would be very helpful to pack makers and players who want to fine-tune their experience with Terraforged.

**What considerations for gameplay/performance/user-experience should be made:**

Maybe have a warning in the config file, telling you to be careful on what you put where as you could end up with pretty weird results if you put the wrong biome in the wrong place.

**What alternatives or examples have you considered:**

Alternative: I tried to set some biomes weights to 0 in the biome_weights.conf, and tweak the weights of others but ultimately it doesn't solve the issue of misplaced biomes or changing biomes to another location/terrain.

Examples: 

1. In the attached image, you can see that the biome byg:oasis is misplaced in the Medium Wetlands section when it should be in the Warm Wetlands section. While this is probably an issue coming from BYG, players/modpack makers should be able to correct this issue with a config file.

2. I am currently making a modpack. I would however like to change where some biomes spawn in order to have more variety and lighten up some climates: some regions straight up have no biomes attached to them (Lake Warm, Coast Warm, or Wetlands Warm for example) while others have an excessive ammount. I would also for example like to change BYG's rainbow beach and white beach to be in the Warm Beach category instead of the Medium Beach.

![Screenshot 2020-11-19 225121](https://user-images.githubusercontent.com/43299926/99728463-c35e8500-2ab9-11eb-8941-189eb2e6530b.png)

**Comment by xynerorias** [comment]
I guess Terraforged's automatic biome handling is using things like biome temperature, elevation, precipitation, etc.. for assigning a custom biome to a terrain but sometimes.

Here with BYG's case, either Terraforged gets it wrong, or the biome isn't assigned a "correct" temperature/category/others (so an error on BYG's end). Or sometimes it could even be both Terraforged and the biome mod's fault.

This is the main issue I'm addressing, users should be able to configure biome mapping to both address this type of issue, and also to allow further customization should the user want to.

**Comment by Won-Ton** [comment]
It's a single digit change on BYG's end to fix a temperature or whatever, whereas a considerable amount of work to support changing it on TF's.

This won't be added to 1.15.2 since efforts are focussed on 1.16.

Come 1.16 you can probably change biome properties via datapack and if it's not possible via datapack then there's scope within forge's new biome api to write a very simple mod that manage this sort of thing.
