### ISSUE TITLE
Question about BoP and new versions

### ISSUE THREAD

**Issue by Barerock** [TerraForged/TerraForged#294]
I had issues with BoP and the 0.0.15 version of this mod. Generally BoP biomes either _never_ spawned or spawned erratically and rarely. Things like volcanoes never appeared, neither did magic biomes or other things. other mods like Autumnity and Bloomful worked perfectly and, honestly, a little too well (Spawning more often than not). Using the Nature's Compass mod and zooming at mach 12 across the world didn't reveal new things more than 95% of the time, and I think I only experienced 2 or 3 BoP biomes out of a few dozen non-BoP biomes.

I was wondering if the 0.1.3 version, which has a huge amount of fixes compared to my current version, fixes the bad generation of BoP biomes with TerraForged; I did note that there is a patch for better compatibility, though Idk what it entails.

Thanks a lot for the mod, I just wanted to know what I should expect and whether I would need to reinstall either if it just decided not to work (like a previously posted issue said they had to do).

**Comment by Won-Ton** [comment]
try it
