### ISSUE TITLE
How do I build this mod for Fabric? (+build help question)

### ISSUE THREAD

**Issue by RowanSkie** [TerraForged/TerraForged#31]
The answer for "Is this possible for Fabric" has been answered so I ask how to build it instead. Never really tried building Minecraft mods before...

**Comment by RowanSkie** [comment]
So, I forked, and I'm trying to make my own build but I have an error instead:
> C:\Users\markz\Documents\GitHub\TerraForged\TerraForgedMod\src\main\java\com\terraforged\mod\chunk\fix\ChunkCarverFix.java:36: error: ChunkCarverFix is not abstract and does not override abstract method setLight(boolean) in IChunk
> public class ChunkCarverFix implements ChunkDelegate {
>        ^

Have any hints?

**Comment by dags-** [comment]
Hi, the project is set up to be built with the `publish` task - this defers reobfuscation of dependency modules which appears to be the issue you're seeing there. I don't know if fabric's toolchain works the same or if they have some other way to build multi module projects

**Comment by RowanSkie** [comment]
> Hi, the project is set up to be built with the `publish` task - this defers reobfuscation of dependency modules which appears to be the issue you're seeing there. I don't know if fabric's toolchain works the same or if they have some other way to build multi module projects

I'm using Apache Netbeans, what should I use then?

**Comment by dags-** [comment]
`publish` is just another gradle task. I'm not familiar with netbeans or how it integrates gradle, nor am I that knowledgable about fabric tbh. You might be better off asking for some pointers on a fabric modding discord or something

**Comment by RowanSkie** [comment]
> `publish` is just another gradle task. I'm not familiar with netbeans or how it integrates gradle, nor am I that knowledgable about fabric tbh. You might be better off asking for some pointers on a fabric modding discord or something

I don't have that gradle task in mine, both VSCode and NetBeans. I haven't really done anything yet.

**Comment by dags-** [comment]
It's provided by the maven-publish plugin which is declared in my gradle.build file. I don't know how either of those IDE's go about importing gradle projects, sorry I can't be of more help

**Comment by RowanSkie** [comment]
Maybe one last question then, which if the projects should I build?

**Comment by dags-** [comment]
You can run the publish task on the root project. The actual mod jar is built under the TerraForgedMod sub-project (that is, the mod jar appears in `./TerraForgedMod/build/libs/`
