### ISSUE TITLE
River Improvement.

### ISSUE THREAD

**Issue by GamingInfinite** [TerraForged/TerraForged#33]
_Please take a look through the [existing enhancements](https://github.com/TerraForged/TerraForged/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aenhancement+) to see if yours has already been suggested. Feel free to add your own thoughts to the thread :)_

The feature that I would like to see is not related to a problem.  The feature that I propose is to make the rivers actually flow.  Not like the way it currently is where it actually goes from the source to the ocean, but to make the blocks flow in the direction the river is meant to be flowing.

The primary reason I suggest this is because there is a mod that I like to play with in 1.12 that does this, and I understand that it's not a priority, but I feel that there are a lot of people that would like this feature, as part of the mod or as a companion mod for this mod.

**Comment by dags-** [comment]
Hi, I've looked into this previously but there are technical limitations to acheiving the effect.

A mod like Streams only works over a (relatively) limited distance so their method wouldn't work for TerraForged.

I've seen another worldgen mod attempt it at a scale closer to TF but personally I felt the results actually detracted from the overall quality of the rivers in that, and also introduced other problems in the terrain elsewhere.
