### ISSUE TITLE
Smaller continents / Islands

### ISSUE THREAD

**Issue by Scarecrow-01** [TerraForged/TerraForged#34]
Me and my team were trying to create a map for our server using the preset tool to get bigger oceants and smaller continents in order to simulate and islands-only world but we quickly found out that the whole thing isn't really possible.
Even setting the land size to the lowest value gives enormous islands and reducing the ocean size didn't help.

**Suggestion:**
Whjat I'm suggesting is an option to make even smaller continents or rather a way to only generate islands.

Beside being a vital aspect of our project, I can see this feature helping lots of players who just want to play in a maritime world, traveling using a boat and generally seeking an experience similar to the good ol' Islandcraft

**Comment by dags-** [comment]
I can change the lower-limit on the continent slider to allow smaller values. This coupled with increasing the ocean size would allow for more island-like landforms.

**Comment by Scarecrow-01** [comment]
> I can change the lower-limit on the continent slider to allow smaller values. This coupled with increasing the ocean size would allow for more island-like landforms.

Thank you! :D

Will it be possible to test this new feature in an upcoming BETA-version or something along those lines? :)

**Comment by dags-** [comment]
Added to 0.0.5
