### ISSUE TITLE
Is it going to be ported to the minecraft W10 edition ?

### ISSUE THREAD

**Issue by Weavan** [TerraForged/TerraForged#35]
I am a long date player of the java edition and I just started to play on the w10 edition since a friend of mine can join my world with a switch. I really don't know a lot about the windows 10 edition, I don't even know if it is modable so it might be dumb to ask this.

In clear :
- Is it possible to make a w10 ed ?
- If yes, is it going to happen ?
- In a last effort, if I load a word on java with the mod, then I convert it into w10, and play on this version, am I going to have troubles whith the world generated after the conversion ?

Thank you, I am not used to github but your work is amazing and I felt it was time to ask my questions here

**Comment by dags-** [comment]
Hi, thanks for dropping by :)

- _Is it possible to make a w10 ed? & If yes, is it going to happen ?_
Not currently, and I doubt that W10 will ever support modding the world-gen to the extent that is needed to do achieve the things that TerraForged can do on Java Edition

- _Can I generate a TF world in java and convert it to W10?_
I'm not sure, sorry. I don't know what tools are available to convert worlds to W10 or whether they'd work with java-modded worlds. I'd be interested to hear if this is possible myself!

**Comment by Weavan** [comment]
Thank you for the quick answer ! 
That's what I feared, I had few hopes about it.

I may try this myself to see if the last option work.
You did a great work, thanks for your time !

**Comment by RORIdev** [comment]
To be honest, worlds can be converted between versions `(latest stable -> latest stable)` using [`Universal Minecraft Editor`](https://www.universalminecrafteditor.com/).
