### ISSUE TITLE
Potential improvements for preview GUI

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#38]
Change color of snowy biomes to a more white color. Currently it's easy to confuse them with deserts.
![Screenshot_1](https://user-images.githubusercontent.com/33978024/76517644-555fb980-6466-11ea-891c-08065d5d926f.png)

Invert temperature colors so red is hot and blue is cold.
![Screenshot_2](https://user-images.githubusercontent.com/33978024/76517642-54c72300-6466-11ea-8393-ee261ee9f0fb.png)

Invert precipitation colors so red is dry and blue is wet.
![Screenshot_3](https://user-images.githubusercontent.com/33978024/76517640-5395f600-6466-11ea-968e-1fc2e624bb8d.png)

Add or replace biome shape mode with terrain type (which may be more useful visually).

Not critical but would be nice:
Add a circular ruler with distance slider which shows estimated walk time to help visualize terrain scale. (1 day of walking = 4096 blocks)

**Comment by dags-** [comment]
Oh that's dumb. At some point I've mixed up the colour calcs from temperature & moisture.

The tundra colour is as you/Monster requested. I'd prefer a shade of white too

**Comment by CreativeRealms** [comment]
I had no input in the colors as I preferred Monster to do it as he's the artist. However I think if we both think that color should be changed it wouldn't hurt to do it.

**Comment by dags-** [comment]
Added the colour fixes
