### ISSUE TITLE
Set spawn biome, or set worlds to spawn with a predetermined seed

### ISSUE THREAD

**Issue by foxanthony1** [TerraForged/TerraForged#41]
I'd like to be able to dictate the biome the players spawn in, somehow.

Actually, I want players to spawn on islands, which someone has already suggested. For server play it would be great to have players be able to spawn on different islands.

I'm always interested in comprehensive terrain gen mods and you look like you're doing the work. I appreciate that, I know these things aren't trivial. Thanks.

**Comment by dags-** [comment]
I'd see spawn biome selection being a thing - there's already the functionality for this in vanilla code but I currently just use the default choices.

I don't feel like spawning per continent/island really fits within TerraForged's scope. Seems more like a gameplay mechanic that some other mod/plugin would provide.
