### ISSUE TITLE
Beach biomes with turtles in land-locked areas

### ISSUE THREAD

**Issue by davemyb** [TerraForged/TerraForged#42]
I just tried this out last night and it looks incredible! Very nice work! One thing that I noticed as I was flying around the world was that there were a LOT of turtles around. Not a big issue but when I saw them in the what I thought were desert areas, I thought it was odd. Turns out the deserts  were beach biomes. so I figure this is some sort of bug.

I was using the defaults to generate a world, so reproducing this might be hit and miss. I only tried the one world, so I don't know if this happens all the time.

**Comment by dags-** [comment]
Yeah you do get the occasional area where land-locked beaches/oceans form.

This due to the way that the continent/island shapes are distorted and are pretty much unavoidable under the current system without making coasts much straighter :/

**Comment by davemyb** [comment]
Ah, OK, I get it. That's a bummer - more turtle farms! :)
