### ISSUE TITLE
How do I set up this with biomes o' plenty?

### ISSUE THREAD

**Issue by radroachhd** [TerraForged/TerraForged#43]
I read the faq on the forge webpage, stating that this would work with other mods featuring biome generation with new blocks such as biomes o' plenty; how would I exactly go about setting this up since both mods seem to need to have world type set before generating?

**Comment by dags-** [comment]
Assuming you want TerraForged's terrain, you'd use the TerraForged world type. It'll look for any mod biomes that have been registered as 'overworld' biomes (BoP's ones are) and make a best effort to use them in places that make sense.

**Comment by radroachhd** [comment]
Ah, thank you; seemed to work great!
