### ISSUE TITLE
Rivers have icebergs generating in them

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#44]
TerraForged-1.15.2-0.0.4-157

![2020-03-12_22 55 48](https://user-images.githubusercontent.com/33978024/76566289-19a01080-64b5-11ea-825d-5899030e63a6.png)

**Comment by dags-** [comment]
The iceburgs need a little more work in general. They don't fade out towards biome edges either, so sometimes just cut-off abruptly at borders with other biomes.

I should be able to clean this up in one go

**Comment by Quizer9O8** [comment]
The reason icebergs get into the river that close is has to do with the fact that small bits of cold/frozen ocean are inside of the river biome itself. I had it also happen with dolphins spawning deeper inland because some ocean bits were inside the river too.

**Comment by dags-** [comment]
This should be fixed as of 0.0.8
