### ISSUE TITLE
No Villages?

### ISSUE THREAD

**Issue by y-fu-for-li-fu** [TerraForged/TerraForged#45]
I can't seem to find any villages that generate with this mod. Is this a known problem?

**Comment by CreativeRealms** [comment]
I've found some
![2020-03-13_10 33 57](https://user-images.githubusercontent.com/33978024/76603771-3e78a000-6516-11ea-85b0-fc1b3d9a5c49.png)

**Comment by dags-** [comment]
Also, there are sliders to control the distance between different types of structure.
