### ISSUE TITLE
World Generation Gets Truncated on server

### ISSUE THREAD

**Issue by Akulav** [TerraForged/TerraForged#46]
**Description**
The world loaded in single-player and placed for the server, as in documentation. The world is generated using the terraforged mod only the chunks which where loaded in singleplayer. 

**How to reproduce
Generate custom world in singleplayer.
Place it on a forge server. 
Walk until the edge of the chunks loaded in singleplayer.

**Additional information**
![Untitled](https://user-images.githubusercontent.com/43496076/76617889-e3ec3d80-652f-11ea-88cd-a9b8c0d5844d.png)

NOTE!!! TerraForged is installed on the server

**Comment by dags-** [comment]
You need TerraForged to be installed on the server if you want the world to continue to generate with it

**Comment by Akulav** [comment]
it is installed

**Comment by dags-** [comment]
In that case, could you provide your server `debug.log` file please?

It might also be helpful for me if you could upload the `level.dat` files from the single-player and server worlds respectively (you might need to zip them to upload to github)

**Comment by Akulav** [comment]
[Debugs.zip](https://github.com/TerraForged/TerraForged/files/4329467/Debugs.zip)

everything is in here. I am using some other mods, but I assure you that if I isolate only Terraforged, the issue persists.

**Comment by dags-** [comment]
Something is causing forge to fail at reading the registries stored in the `level.dat` (probably something that was present when creating the world in single player but not there on the server?).

Anyway, the knock-on effect of this is that the generator-type and generator-options do not get loaded so the server defaults the world to vanilla gen.

I can't tell you exactly which mod provided the registry entry that is missing/causing the problem.
There is reference to `mrcrayfish.vehicle` in the error, but this may be a false-positive

**Comment by Akulav** [comment]
you are right, removing the mod fixes the problem, even if it is very odd. You aren't meant to provide a fix this, although I would be thankful.
