### ISSUE TITLE
Simple chunk preloading

### ISSUE THREAD

**Issue by Akulav** [TerraForged/TerraForged#47]
**Is your feature request related to a problem? Please describe.**
Hosting a forge server on a low power PC comes with some hiccups. Having the possibility to preload an area around the spawn will increase significantly the size of the world, but decrease the cpu usage.

**Describe the solution you'd like**
Lower cpu usage because the chunks are already generated and they just need to be loaded into memory.

**Describe alternatives you've considered**
There is an alternative, but for 1.12.2 only, 
[https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator](url)

**Comment by dags-** [comment]
Hi, I also make this utility mod:

https://www.curseforge.com/minecraft/mc-mods/pregenforge

**Comment by Akulav** [comment]
nice, I looked a lot for such a mod, but could not find any. Amazing how it evaded my searches.
