### ISSUE TITLE
Mod Incompatibilities (generating terrain with bad blocks)

### ISSUE THREAD

**Issue by zedekblue** [TerraForged/TerraForged#50]
**Description**
I'm not entirely sure how Terraforged chooses what blocks are "natural" enough to use in normal worldgen, but it seems to have some issues with choosing blocks that aren't "natural" in some other mods.
The three I've encountered are:
[Security Craft](https://www.curseforge.com/minecraft/mc-mods/security-craft) - Reinforced blocks are being spawned and are unbreakable, as they are "owned" by a nonexistant "player".
[Macaw's Roofs](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs) - "Roof Straight Base"'s are being spawned under dirt level in what seems to be many jungle biomes.
[Tubes Reloaded](https://www.curseforge.com/minecraft/mc-mods/tubes-reloaded) - "Distributor" is being spawned under ~~mesa~~ badlands biomes.

**How to reproduce**
- This happens regularly with the mods installed

**Additional information**
Since I'm just trying to help development and not spend 3 hours narrowing down the issue, I haven't tested this outside my modpack with only the conflicting mods installed. This is an unmodified (aside from Terraforged being added) [All The Mods 5-1.10 modpack](https://www.curseforge.com/minecraft/modpacks/all-the-mods-5).
This modpack includes Biomes o Plenty.

**Comment by ThatGravyboat** [comment]
Other Blocks are being added to world gen are also 
[Beesourceful](https://www.curseforge.com/minecraft/mc-mods/beesourceful) - All honeycomb blocks are being added under the dirt level.
[COMBAT](https://www.curseforge.com/minecraft/mc-mods/c-o-m-b-a-t) - Adds Purified Grass Block under the grass layer.

**Comment by dags-** [comment]
As of 0.0.4 TF will not actively use other mods' blocks in base-gen.
Third party mods can add their blocks to the world-gen block tags listed on my wiki.

**Comment by HellishINC** [comment]
.3 was generating massive amounts of basalt/marble (and preventing ore gen) from bluepower but now with this change, it doesn't spawn at all.
