### ISSUE TITLE
doesnt appear un world type when creating new world

### ISSUE THREAD

**Issue by brogobkanob** [TerraForged/TerraForged#51]
i put the file in the mods folder in .minecraft and i opened up both 1.15.2 and 1.15.2-OptiFine_HD_U_G1_pre9.  

the optifine one shows 1.15.2 (Modded) in the bottom left of the main menu of minecraft
i go to click create new world and i go into more world options and terraforged doesn't appear in the world types section

**Comment by CreativeRealms** [comment]
Optifine with 1.15.2 doesn't work with Forge currently so you'll have to use TerraForged and Forge for 1.15.2 without it.

**Comment by brogobkanob** [comment]
it doesn't say modded in the bottom left corner when i open normal 1.15.2 and it doesnt show the world type

**Comment by Monsterfisch** [comment]
you need to use the forge profile not the vanilla 1.15.2 one you can get forge from [here ]( http://files.minecraftforge.net/)run the installer and select the right profile it should work then
