### ISSUE TITLE
TerraForge world is not being generated (Server)

### ISSUE THREAD

**Issue by meisterzorn** [TerraForged/TerraForged#52]
So the problem is, that i own a Nitrado Server and want to use TerraForge on it. I installed TerraForge itself on the server and imported a own SinglePlayer world into the server folder. Problem is, everytime I change the server-properties to "level-type=terraforged" and restart then join the server, the properties seem to reset and the default world generator generates the world. How can i make it, that the properties stay on terraforged and generate the world with TerraForged?

**Comment by CreativeRealms** [comment]
2) "How can I use this on my server?"
When Forge supports it, you can simply set level-type=terraforged in your server.properties file. In
the meantime, you will need to create the world in single player and then copy that to your server
directory. (In both cases, TerraForged must be installed on the client and the server).

**Comment by meisterzorn** [comment]
> 1. "How can I use this on my server?"
>    When Forge supports it, you can simply set level-type=terraforged in your server.properties file. In
>    the meantime, you will need to create the world in single player and then copy that to your server
>    directory. (In both cases, TerraForged must be installed on the client and the server).

Still did not help me in any way. When i set the level-type to terraforged and upload the single player world into the server, it generates the first chuck where i spawned in with terraforge and then generates the rest with the default generator.

**Comment by CreativeRealms** [comment]
Forge doesn't support level-types yet so you need the mod on the server before you open the world you generated in SP. If that still doesn't help you need to pre-generate a large area so that the chunks will load properly.

**Comment by meisterzorn** [comment]
I added the terraforge mod on the server in the mods folder and i somehow still doesnt work

**Comment by CreativeRealms** [comment]
I assume you still have it on your client?

**Comment by meisterzorn** [comment]
Yes, i have it on my client. I put it in the mods folder, generated a world in single player with terraforge, then copied it onto my server, set my server.properties to level-type=terraforged and then started the server. The first chunk is normal (the spawn chunk) but then the chunk is cut off and it looks like the default generator was used

**Comment by CreativeRealms** [comment]
Don't set the level-type to anything (besides the default value) as it's not supported. I have no clue if that will fix the problem but I'm going to try setting up a server on my end (since I have not tested any of this) to see if I can recreate the problem.

**Comment by meisterzorn** [comment]
Thank you. Would help me greatly if you can somehow fix it.

**Comment by dags-** [comment]
Not being able to set level-type to modded worlds in the server.properties is a forge issue not a TF one, it might help prompt them to fix it if more people direct their use-case to them.

For the work around method (generating in single-player and copying the world to the server), please provide the debug.log from your server. Should be able to tell from that what is going wrong rather than blind guessing :)

**Comment by CreativeRealms** [comment]
After testing it on my end everything is working.

**Comment by meisterzorn** [comment]
> Not being able to set level-type to modded worlds in the server.properties is something forge needs to support, not TF. An [issue](https://github.com/MinecraftForge/MinecraftForge/issues/6189) has been raised and I have submitted a [proposed fix](https://github.com/MinecraftForge/MinecraftForge/pull/6545). I can't do much more than that.
> 
> For the work around method (generating in single-player and copying the world to the server), please provide the debug.log from your server. Should be able to tell from that what is going wrong rather than blind guessing :)

How can i access the debug.log? Cant seem to find it one the web.interface of the server

**Comment by dags-** [comment]
No idea. Contact your server provider. In a normal server setup there is a folder called 'logs'

**Comment by meisterzorn** [comment]
I tested the server without using any other mod and now it seems like it works. I only used JEI,Ambient Sounds and macaws windows but apparently the caused the problems. I will still upload the debug.log from the current running server and later i will upload the debug.log from the server with those mods. Maybe you guys can find a incompatiblity with the mods and terraforge.
[debug.log](https://github.com/TerraForged/TerraForged/files/4334249/debug.log)

**Comment by meisterzorn** [comment]
It could also be, that i used the TerraForge 0.0.3 version up till now and just updated to th 0.0.4 version so maybe that has fixed that

**Comment by dags-** [comment]
More likely that stripping things back and doing things methodically corrected whatever mistake had been made before. Glad you're up and running!

**Comment by meisterzorn** [comment]
Ok current situation. After i added the mods back in, the server is unjoinable and starts and shuts down the entire time. I will upload the current debug log
[debug (with mods).log](https://github.com/TerraForged/TerraForged/files/4334258/debug.with.mods.log)
