### ISSUE TITLE
gamerule doMobSpawning false not working in TerraForged world type

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#53]
**Description**
Just as the title describes the command `/gamerule doMobSpawning false` does not work in the TerraForged world type.

**How to reproduce**

1. Create a new world with **TerraForged** as world type

2. Set gamemode to **Peaceful**

3. Use the command `/gamerule doMobSpawning false`

4. Use the command `/kill @e[type=!minecraft:player]` to kill all remaining mobs

5. Fly into new chunks and you will still see passive mobs spawn

**Additional information**
_No additional information_

**Comment by dags-** [comment]
This appears to be a vanilla bug actually (happens in the default world type too). `doMobSpawning=false` only prevents mobs from spawning during the world tick but they are still spawned as part of chunk-gen :/

**Comment by dags-** [comment]
(Added a fix in 0.0.5)
