### ISSUE TITLE
Cannot see my character ingame, no block destruction animations.

### ISSUE THREAD

**Issue by durrnavy** [TerraForged/TerraForged#54]
Cannot see my character in game. My hotbar shows up but my hand doesn't. Cannot see myself in f5 mode either. No animations when breaking blocks either.
![image](https://user-images.githubusercontent.com/62196714/76695756-e2fe0c00-66e7-11ea-91f6-e7a656add15f.png)

**Comment by SirZombz** [comment]
Same.

**Comment by CreativeRealms** [comment]
What version of Forge are you using?

**Comment by durrnavy** [comment]
31.1.20

**Comment by CreativeRealms** [comment]
Downgrade to 31.1.9

**Comment by durrnavy** [comment]
Thanks, this fixed it.
