### ISSUE TITLE
Strongholds spawn above ground when underwater.

### ISSUE THREAD

**Issue by CreativeRealms** [TerraForged/TerraForged#55]
v0.0.4

**Comment by CreativeRealms** [comment]
This still happens in v0.1.0. Would recommend limiting Stronghold spawning to land and shallow oceans as deep oceans are below the vanilla y 30 range that Strongholds spawn in.

**Comment by dags-** [comment]
The problem with that sort of approach is that you potentially cut off important parts of the stronghold when they extend into deep ocean like that
