### ISSUE TITLE
World pre-generation

### ISSUE THREAD

**Issue by Sam-pie** [TerraForged/TerraForged#59]
Hello! I was wondering, if the mod changes the way the terrain generates without adding new blocks but only by rearraging the vanilla blocks, wouldn't it be possible to generate a world, and then use it in vanilla?

From my understanding (which is close to none) the mod has to be installed for new chunks to be generated with this technique, so wouldn't it be possible to pre generate a world, with all needed chunks already loaded and upload it to a server, like you would do for a custom map?

**Comment by dags-** [comment]
Hi, I don't provide support for it but there's nothing stopping you trying :)
