### ISSUE TITLE
# bug/enhancements Problem with current world generation

### ISSUE THREAD

**Issue by NecroTech1171** [TerraForged/TerraForged#60]
Having a problem with the current state of the world generation. 

1) Trees are more realistic yes but gets old having to dig 3 blocks down to chop the stumps out then cover up with dirt(Note: Mine colonies Mod also has a bug where the villager A.I wont dig the 3 stumps down in the dirt and ignore those and move on)

2) Oceans look way more nice but have looked everywhere for the clay splotches you would normally find in the ocean but have found none anywhere, even when digging. (Note: would be helpful to have clay spawn around the oceans or just anywhere under the dirt in random splotches because clay is a resource needed in Mine Colonies to make shingles)

3) Diamonds seem more scarce and harder to find and the cobblestone you would normally find covering about 70 percent of the world under the dirt is now ranging to about 20 percent and more painful to dig for. Past that i do like how the gold spawns closer to the surface like the red-stone ore now, that's a helpful and nice addition.( would be more beneficial if you made cobblestone about 35 percent more common to find and diorite and andesite and granite dulled down about 25 percent since they really arnt used that much in game, Past that would be helpful to make diamonds and emeralds spawn more commonly since they feel nearly impossible to locate rn).

4)Having tress spawn in the middle of rivers and you have to get out of your boat to chop them down so you can further your journey down the river. Then wish rivers could have a erosion mechaniche built in similar to the water erosion mod to where very slowly they will erode and become bigger and deeper to maybe a max of 24 blocks in width to 21 blocks deep unless blocked off by stone brick blocks or any block other then dirt, clay, wood which would rot over time and break apart, sand, gravel, and cobblestone which would also rot and break apart. Then also having some smaller islands spawn thru out the ocean would also become a nice addition to the world generation.  {Note: would also be very helpful if there is a way you can go into world edit under the main menu after selecting the world to re-optimize it and also add any changes you have made to the mod via mod updates to keep players from having to start a new world to see the enhanced changes if this is even possible somehow)

**Comment by m5w** [comment]
Can ores spawn inside andesite, diorite, or granite?  That could explain the seemingly lower ore spawn rates.

**Comment by NecroTech1171** [comment]
> Can ores spawn inside andesite, diorite, or granite? That could explain the seemingly lower ore spawn rates.

I've been playing map I made 2 days ago and searched everywhere thru a large system of caverns and only found a total of 22 diamond and 0 emerald where on vanilla Minecraft diamond and emerald seemed to spawn more and be a little easier to find. I'm mostly just finding diorite, granite, and andesite now and little cobbstone compared to vanilla and it feels really rare to find diamond and almost impossible to find emerald. So I'm asking if the generation could be improved to make cobblestone spawn more then andesite, granite, and diorite and if you could up the spawn rate for diamond and emerald so you can come across them just as easily as you could on vanilla Minecraft. Then past that I still can't locate any clay spawns. Looked in the jungle because someone told me to try there because they found some there and no luck. Then the trees being 3 blocks below ground lvl doesn't work well with minecolonies mod and gets old having to cover up all the holes from digging 3 logs down. Past that the mod is absolutely breath taking and still has work to do but no other world generation mod can compete. This mod alone breaths images of what minecraft worlds should be like. I love it and thank you so much for your dedication and hard work.

**Comment by m5w** [comment]
Oh, just to clarify, I haven't worked on the mod.

> I'm mostly just finding diorite, granite, and andesite now and little cobbstone compared to vanilla and it feels really rare to find diamond and almost impossible to find emerald.

I've been having the same experience.

**Comment by dags-** [comment]
On clay: https://github.com/TerraForged/TerraForged/issues/62
On trees: https://github.com/TerraForged/TerraForged/issues/32
On ore-gen: https://github.com/TerraForged/TerraForged/issues/40

Please try to keep issue threads related to a single subject (like the above examples) as it becomes quickly unmanageable trying to discuss multiple different concepts in one. It also means anyone interested in just that particular thing can watch that thread and follow it's progress to resolution.

Feel free to open new bug/enhancement ticket(s) for anything not covered by the above linked issues.
