### ISSUE TITLE
Default to Terraforged Worldtype

### ISSUE THREAD

**Issue by Darth-Pikachu** [TerraForged/TerraForged#61]
When people create a world, they more often than not use the world type that's defaulted, or they use biomes o' plenty, because it can be assumed the default worldtype setting is the correct way to play a modpack.

I would like to see a config option to default to the terraforged worldtype on world creation. Alternatively, there could be config option to use terraforged regardless of world type if someone defaults to another worldtype.

**Comment by dags-** [comment]
This would be better suited to some third-party modpack utility mod
