### ISSUE TITLE
Missing clay

### ISSUE THREAD

**Issue by perecnicek** [TerraForged/TerraForged#62]
**Description**
I can' find clay anywhere in the world and i need it very much for minecolonies mod. 

**How to reproduce (get your mind out of the gutter! -_-)**
- I using 0.0.3 version of the mod

**Comment by HellishINC** [comment]
I can confirm the same issue on 0.0.3. Clay was nonexistent in oceans, rivers (which were very rare as well) and lakes. Never found a single piece of it what so ever.

Can't say if the issue still holds true for >=0.0.4 as I have compiled quark and that adds clay to worldgen.

**Comment by perecnicek** [comment]
> I can confirm the same issue on 0.0.3. Clay was nonexistent in oceans, rivers (which were very rare as well) and lakes. Never found a single piece of it what so ever.
> 
> Can't say if the issue still holds true for >=0.0.4 as I have compiled quark and that adds clay to worldgen.

quark is for version 1.15.2 ?

**Comment by HellishINC** [comment]
Yes/No. You can compile the git version yourself either way that is irrelevant to this mod.

**Comment by dags-** [comment]
Clay generates as part of the strata layer system, so there are regions where it can be found between the top grass block and first stone layer, other regions won't have it at all.

Obviously if you disable the strata decorator then it won't be found anywhere which I understand can be a problem for gameplay. I'll look at reintroducing it to river/ocean areas

**Comment by HellishINC** [comment]
I have not touched any settings as not all are clear as to what they do (like fade). This is true for both in game and toml configurations.

Regarding feature generation, are there any plans to make it configurable? By that I mean, it would be fantastic if the user could choose how often ravines/caves generate. Being able to control the frequency of certain stone types would also be desireable. Currently I'm seeing most worlds generate with virtually all non cobble stones. This means that a players are forced to use wooden tools for extended periods of time as they can not craft a furnace and, in the case of modded, can't make stone tools. Perhaps having the option to generate the worlds shape only (and not any of the rock block type functionality).

**Comment by dags-** [comment]
Reminder to keep discussion relevant to the issue thread. Open a new ticket if one doesn't exist for the thing you want to discuss/suggest

**Comment by demonJ5** [comment]
> Obviously if you disable the strata decorator then it won't be found anywhere which I understand can be a problem for gameplay. I'll look at reintroducing it to river/ocean areas
Likewise, a similar issue occurs for the decorative stone blocks for andesite, marble, and granite.
Could we see an option to introduce "globs" of them like in vanilla minecraft?
https://i.imgur.com/PlPd7id.png

**Comment by dags-** [comment]
In the next update (0.0.5) the generator will revert to using the stone blobs when strata is disabled
