### ISSUE TITLE
Mountain weight

### ISSUE THREAD

**Issue by koenkaan** [TerraForged/TerraForged#64]
When changing the Mountain Weight, in world generation options, to zero Minecraft will stop functioning.

**Comment by dags-** [comment]
What version are you using?

**Comment by koenkaan** [comment]
0.0.3

**Comment by dags-** [comment]
Thanks, found the cause of the issue. Will be fixed in the next update (0.0.5)

**Comment by JTandT** [comment]
This bug also applies to Badlands and Volcanoes in addition to Mountains in 0.0.4
