### ISSUE TITLE
Stone walls placed every chunk row

### ISSUE THREAD

**Issue by grizzlybear1024** [TerraForged/TerraForged#65]
+/-Z Stone walls are placed on the east side of chunks in high elevation places when Strata Decorator is turned off

**Strata Decorator: on**
![2020-03-17_21 05 16](https://user-images.githubusercontent.com/32884451/76924444-863f5480-6893-11ea-8628-de1c0df92e61.png)

**Strata Decorator: off**
![2020-03-17_21 05 37](https://user-images.githubusercontent.com/32884451/76924453-8e978f80-6893-11ea-8323-71e4fc6d209a.png)

coordinates: 372 136 1646 in seed -5164717965812993546
default settings except for strata decorator

**How to reproduce**
- Standard Mojang Launcher on Arch Linux
- Turn Strata Decorator to off
- No other mods
- (PC Specs if you need them): 
 - Intel i5-7300HQ
 - Nvidia GTX 1050 Ti Mobile
 - 16GB RAM

**Comment by Tacoburger** [comment]
I also have the same issue in my multiplayer game.
https://i.gyazo.com/f14f8f83e13cc190aace9d10ff454cfb.png

**Comment by demonJ5** [comment]
Additional pictures. These were not taken with default settings, however.
https://imgur.com/a/TY58GJ6
Settings used for terraforged-generator.json
https://pastebin.com/WmYxs7gj

**Comment by dags-** [comment]
Yep. Will be fixed in the next update
