### ISSUE TITLE
Unable to run world on a server

### ISSUE THREAD

**Issue by Mb6123** [TerraForged/TerraForged#66]
**Description**
I am aware of other issues, though none of the solutions appear to be making a difference in my outcome.
After following all the instructions i could find on how to make this mod properly work on a server, I was unable to make it work. I create the world in a single player world, everything works fine, but when I move it over to a server, [this](http://prntscr.com/rifxme) happens.
I also get an error saying [this](https://hastebin.com/ikuketofin.md).

**How to reproduce**
I currently an using no client-side mods or server-side mods other than TerraForged.
As to how to recreate the error, i am unsure. I am using the most recent version of forge and nothing fancy other than that.

**Comment by Larky2k** [comment]
You have got the same mods server side and client side.

**Comment by tadeseus** [comment]
Have you moved the TerraForged-xxxxxxxxx.jar into the mod folder of the server?
It seems like you created a world in single player, but dont have the mod installed on the server.
Thus any new chunks that are generated are generated with the default world generator and not TerraForged.

Also:
Are you running a Forge or a bukkit server?
I had the "Ignoring unknown attribute 'forge.XXX" when trying to run the mod on a bukkit server

**Comment by tadeseus** [comment]
Okay I just had a similar bug but without the errors.
I solved the problem with the following steps:
1. Stop the server
2. Delete the world
3. Restart the server and join it
4. Stop the server
5. Delete the default generated map
6. Copy in the terraforge map
7. Start the server

**Comment by dags-** [comment]
I'd need to see the server logs (preferrably `debug.log`) to diagnose properly, but as tadeseus has pointed out it sounds like you do not have forge and/or terraforged installed on your server.

**Comment by Mb6123** [comment]
Turns out this was actually a Java limitation thanks to me using an old iMac I found laying around. Thanks for all your help though!
