### ISSUE TITLE
Preview image not showing...

### ISSUE THREAD

**Issue by milenko2** [TerraForged/TerraForged#67]
Hello, i found recent problem, when im about to create new world and to customize, the preview doesn't want to show.

Here's screenshot exactly what i mean:
![screenshot](https://user-images.githubusercontent.com/59674985/77006190-50b56c80-6962-11ea-882b-f0743d9f1e29.png)

**Comment by CreativeRealms** [comment]
I have the same issue but after changing the preview mode a few times it shows up.

**Comment by dags-** [comment]
Simply pressing `New Seed` should do it for now. This behaviour wasn't intended though

**Comment by dags-** [comment]
Addressed in 0.0.6
