### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by demonJ5** [TerraForged/TerraForged#68]
**Description**
When moving through the world, the game crashes with an IndexOutOfBoundsException. Moving around more in the same world, the crash seems to be localized to the location in the attached screenshot.

**How to reproduce**
- Using Forge 31.1.0
- Seed: 8418068352463640323
- Generator.json: https://pastebin.com/f4qbM6RJ
- Create world
- Begin moving towards -X, -Z
- Crash will occur when reaching a certain point: https://x0.at/YkI.png

**Additional information**
- Crash log & mod list: https://pastebin.com/ZtzEJLm8

**Comment by dags-** [comment]
Fixed in 0.0.8
