### ISSUE TITLE
Custom Panorama

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#69]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
A custom panorama that encapsulates the essence of TerraForged in one picture.
There should be a config to either enable or disable the panorama.

**Describe alternatives you've considered**
None.

**Additional context**
Try your best.

**Comment by dags-** [comment]
The main menu background thing is up to the resourcepack. I don't intend on overriding that behaviour
