### ISSUE TITLE
Terrain height preview

### ISSUE THREAD

**Issue by damga123** [TerraForged/TerraForged#71]
**Is your feature request related to a problem? Please describe.**
When changing the mountain settings, I find it hard to see what exactly changed. I can see things somewhat change on the preview but I have no idea if more mountains are actually there.

**Describe the solution you'd like**
Having a terrain height option for the preview would make it way easier to see mountains.

**Describe alternatives you've considered**
While the biome_type view is good for seeing biomes, it hard to distinguish things like mountains. Maybe a view that lines up with the blocks that would generate there could work. A mountain has stone and would therefore be gray, that would make it more obvious where mountains are and also other biomes.

**Comment by dags-** [comment]
I've added a cross-section view in 0.0.8
