### ISSUE TITLE
[1.15.2] Compatibility with Lost Cities?

### ISSUE THREAD

**Issue by talayawhite** [TerraForged/TerraForged#74]
Using the Terraforged world type it isn't generating cities/buildings, even with 0.2 "all cities" rarity.
Kinda wondering if it's something to do with how structures are handled? Maybe there's something in the settings I can change to make it work?

BOP also installed, but it generates cities with that world type. (I didn't test extensively to see if it was doing it correctly...)
Also posted in the Lost Cities issues.

**Comment by dags-** [comment]
What version of TerraForged are you using?

**Comment by larry32123** [comment]
> What version of TerraForged are you using?

Im unsure, but its the one off twitch.

**Comment by talayawhite** [comment]
> What version of TerraForged are you using?

I'm using 0.0.7, the one that was updated 2 days ago on twitch.
Also, I just spawned a new world, and happened to be in the middle of an ocean, with an underwater subway right next to me. So... some of it is spawning? But when I teleported to a different biome, still nothing.

**Comment by dags-** [comment]
The problem stems from how LostCities generates its 'dummy chunks' which it uses to obtain heightmap information from the ChunkGenerator.

The 'DummyChunk relies on the generator using a particular method which TF happens to bypass so it doesn't end up recording any height information (although it _does_ have an entire chunk's worth of blocks and heightmaps to derrive that from...)

Regardless, I think I can accommodate without sacrificing too much on my end

**Comment by talayawhite** [comment]
Sweet! Thank You! I was so excited to finally get a good terrain generator, and now I'm even more excited - because who wouldn't love amazing mountain ranges sprinkled with dystopian cities??

**Comment by dags-** [comment]
Change is available in v0.0.8
