### ISSUE TITLE
No controls for Desert Biomes, Ice Spike biomes missing in oceans

### ISSUE THREAD

**Issue by KetaKnight** [TerraForged/TerraForged#75]
When I tried the mod I noticed there are no controls for Desert Biomes in the world generation. The way to get the frequency up for now is to scale down the frequency of all the other biomes. It would however be nice if controls would be added. I've also noticed there are no ice spike biomes generating, although I could understand if these were left out to get a more realistic world. Maybe a toggle for this biome or biomes in general would be nice.

**Comment by dags-** [comment]
There are temperate/moisture sliders in v0.0.8

Ice spikes biomes 100% do spawn, they're just rare
