### ISSUE TITLE
River frequency settings ?

### ISSUE THREAD

**Issue by Zygus42** [TerraForged/TerraForged#76]
Fantastic looking world gen !  

But, I've made 2 worlds and flown around on them for around a half hour each, and have yet to see a body of water that isn't an ocean.  Not a single lake or even puddle and no rivers whatsoever.

The settings for Primary, Secondary & Tertiary rivers appear to be:
    Bed Depth
    Min Bank Height
    Max Bank Height
    Bed Width
    Bank Width
    Fade

I don't see any settings that would increase frequency.  Unless this is affected by the settings under Erosion ?  Tried playing with these, but couldn't see much difference.

TerraForged v0.0.7
forge-1.15.2-31.1.27

**Comment by CreativeRealms** [comment]
There is a slider for river frequency. The rest may be getting looked into.

**Comment by Zygus42** [comment]
There is no slider for river frequency.  Not on any of the customization screens anyway.

**Comment by Zygus42** [comment]
I mean, if there was such a slider, I wouldn't have posted this in the first place correct ??  Please reopen this issue or provide more detailed information.

**Comment by Larky2k** [comment]
It's there, you mite want to get your eyes tested and update to latest Terraforged

**Comment by HolyRadiantPotato** [comment]
Stay polite.
Here is a screenshot : 
![image](https://user-images.githubusercontent.com/62420939/77245983-51305a80-6c23-11ea-943d-e98ba3a246e2.png)

**Comment by Zygus42** [comment]
I counter with my own screenshot:
![image](https://user-images.githubusercontent.com/20757445/77246728-0a635480-6c65-11ea-97c8-38bf8006846f.png)

**Comment by Zygus42** [comment]
And that scrollbar does not go up.

**Comment by HolyRadiantPotato** [comment]
What about the newer version (0.0.8) ?

**Comment by Larky2k** [comment]
Update to latest Terraforged before trying counter.

**Comment by dags-** [comment]
Chill my dudes. The frequency slider was added to v0.0.5. If you don't see it then you're on an older version. 

Check that you only have one version of TF in your mods folder as Forge might be loading an older one without you realising.
