### ISSUE TITLE
Hydraulic Erosion: Rivers

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#78]
**Is your feature request related to a problem?**
The way rivers are currently generated at is a line is drawn from a point inland to a point below sealevel that line than gets distorted to generate the flowing shape of the river because of that distorting the width of the river is also somewhat affected and therefor can create some whacky results on occasion.

**Describe the solution you'd like**
 Instead of drawing a line from a point somewhere inland to a point below sea level you could let  Hydraulic Erosion decide where to put rivers that would form from higher elevations down towards a lake, where two rivers meet and eventually the ocean.

**Describe alternatives you've considered**
None.

**Additional context**
Watch the video(s) in the link down below.
Hydraulic Erosion: []()https://sebastian.itch.io/hydraulic-erosion

**Comment by dags-** [comment]
Doesn't work in a 'real-time' tiled procedural environemnt

**Comment by Quizer9O8** [comment]
Would you mind to explain that a little more?
