### ISSUE TITLE
Can't seem to find stone at all

### ISSUE THREAD

**Issue by Litchytsu** [TerraForged/TerraForged#79]
I've been running around in survival for a while and i don't seem to find stone at all.
is it intended, maybe i missed a parameter ?

**Comment by HolyRadiantPotato** [comment]
The ground is generated as strata of different rocks, so you might find yourself in a world where regular rock is quite deep in the ground

**Comment by Litchytsu** [comment]
i mined down to the bedrock at 3 different spots at about 600 bricks to each others, still can't find any

**Comment by dags-** [comment]
TF generates rock layers in regions - some regions have different combinations and different orderings of stone types. You may have to travel to get away from one rock layer region to a different one that has stone more easily accessible.

If you don't like that behaviour, there is a toggle in the world creation settings called 'strata decorator' - setting that to false restores the vanilla style all stone chunks
