### ISSUE TITLE
River Types

### ISSUE THREAD

**Issue by Quizer9O8** [TerraForged/TerraForged#80]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Give rivers their own secondary terrain type that depends on the surrounding terrain and biome it currently goes through to give it more varation.

**Describe alternatives you've considered**
None.

**Additional context**
This is very content heavy so I recommend you to take a look at this link to make anything out of it:
https://www.popoptiq.com/types-of-rivers/#How_Rivers_are_Classified

**Comment by dags-** [comment]
Rivers will be more varied. They won't be getting new terrain types
