### ISSUE TITLE
More Rivers and other water bodies

### ISSUE THREAD

**Issue by Zygus42** [TerraForged/TerraForged#81]
Awesome world gen !  I know it's still early days for feature requests, but couldn't help myself.

I've been creating some test worlds on v0.0.9 with vanilla and vanilla+BoP biomes, and am finding FAR less bodies of water than I would like to see in my worlds.  

I see the problem in 3 categories:
1) River frequency:
Rivers on the base 1.0 frequency setting are almost unfindable, and even on 5.0 frequency are pretty darn rare.  Extrapolating from the existing settings I would need that slider to go up to around 50.  

2) Lakes:
I have never seen anything that could be called a lake.

3) Side Rivers:
All the rivers I've seen start as a single river at the ocean, spit into 2 at a Y angle and then eventually fizzle out.  There ought to be sideways rivers flowing into the main rivers, especially if there is high terrain around.

Possible solutions:
An excellent example of cool looking rivers and stream can be found in a mod called Streams by delvr.  Now that mod uses special water blocks to create flowing streams and inserts riverbeds out of blocks into the terrain, which is probably outside the scope of what you want to do here, but the results are awesome.  It uses an algorythm that looks ahead of terrain gen to find water sources and then creates a stream to flow into that water source.

There is another mod (fabric only) called Lakeside by Juicebus which adds Lake biomes of different sorts - perhaps this would be an easily added fix to the lack of lakes, as your mod already merges biomes into the surrounding terrain seamlessly.

**Comment by Dragnier** [comment]
I can get behind this suggestion. There is definitely a distinct lack of river/lake formation.

**Comment by HellishINC** [comment]
Also noticed a distinct lack of water on version 0.0.10. Setting myself to creative and flying around in a 3k radius from spawn yeilds zero water unless you're lucky enough to run into an ocean. Out of 8 test worlds, only one had a river that ran for maybe 30 blocks and was one block wide. This is with river frequency set to the maximum allowed.

**Comment by dags-** [comment]
I will be looking at the river finding algorithm for the next milestone release

**Comment by dags-** [comment]
An option to enable vanilla's "lakes" and springs has been added to 0.0.11.
I will be revisiting the river generation system under a separate issue
