### ISSUE TITLE
Slimechunks

### ISSUE THREAD

**Issue by Siraman25** [TerraForged/TerraForged#82]
Hello, I don't know if I'm doing this right, by using /seed and chunkbase.com I'm trying to get to a slimechunk but every one that I tried didn't spawn any slimes. Is it my problem (maybe not waiting long enough) or is it a problem with the mod? Sorry for asking a stupid question. **Thanks to everyone!**

**Comment by dags-** [comment]
Hi, this mod doesn't touch slime spawning mechanics.

Slimes spawn in swamp biomes between y=50 and y=70.
They also spawn in certains chunks below y=40. No idea if the online tools work with 1.15.2 worlds - you could test in a vanilla world I suppose.

**Comment by Siraman25** [comment]
Thank you very much! It will just be my issue then, good to know that the mod doesn't change slime spawning mechanics. Keep up the fantastic work you are doing and have a nice day.
