### ISSUE TITLE
Add Option to Search for Nether Biomes

### ISSUE THREAD

**Issue by demonJ5** [TerraForged/TerraForged#86]
**The problem**

When using mods that add biomes to both the overworld and the Nether to game, you cannot use the Nether biomes with TerraForged enabled; TerraForged seeks out overworld biomes to incorporate into world generation, but it does not do the same for Nether ones. 

An example of this would be Biomes o' Plenty: BOP biomes are present in the TerraForged overworld, but not the Nether. This means that the only way to get BOP Nether biomes is to use the BOP world type and eschew TerraForged altogether.

**Describe the solution you'd like**

I think a toggle in the "Customize" menu for TerraForged that disables or enables the ability to seek out Nether biomes in addition to overworld ones would solve this.

**Comment by dags-** [comment]
I don't touch other dimensions, those just use the vanilla nether/end generators.
There could possibly be an option to redirect to another mod's worldtype for these dims though.

**Comment by demonJ5** [comment]
> There could possibly be an option to redirect to another mod's worldtype for these dims though.

That's exactly what I'm proposing. IIRC Realistic Terrain Gen used to do the same.
