### ISSUE TITLE
More climate controls to allow biasing of certain conditions

### ISSUE THREAD

**Issue by demonJ5** [TerraForged/TerraForged#87]
Not to be confused with the min and max moisture and temperature options that were added in v0.0.8, but is there an RNG bias in TerraForged that prefers spawning colder climates? 

While I have seen the promotional map with the Mesa biome in it, during my and my friends' playtime, we have not encountered a Jungle, Swamp, Desert, Mesa, or Savannah biome-- nor any of the other multitude of Biomes o' Plenty warm climate biomes we have loaded. In contrast, we have found an abundance of everything else from plains to tundras. 

Oddly enough, I have only seen this problem with land biomes. Warm oceans and even coral reefs still spawn quite commonly.

Has anyone else noticed this phenomenon? I'd love to see a desert with this generation.

**Comment by dags-** [comment]
This isn't the effect of a coded-in bias but the result of the climate model that TerraForged uses.

A snow biome occurs where the global temperature is low, whereas a an arid biome would require both high temperature _and_ low moisture, and tropical biomes require high temperature _and_ high moisture.

Further-more, deserts specifically will only occur below certain heights (to avoid sandy mountains etc).

**Comment by demonJ5** [comment]
> The bar for an area to be snowy is lower than it is for desert/tropical areas.
If that's the case, would it be possible to institute a "bias" slider to _increase_ the prevalence of the extremes? That way the spawning conditions could be more easily met.
