### ISSUE TITLE
Weird terrain generation

### ISSUE THREAD

**Issue by koenkaan** [TerraForged/TerraForged#88]
Terraforged 0.0.3 with Biomes o Plenty
I don't have the seed or the exact generation settings. But I do remember that I put the mountain scale at max, as well as the vertical scale. I put the horizontal scale on close to zero.
![2020-03-24_10 45 59](https://user-images.githubusercontent.com/62284650/77412118-bfa92000-6dbd-11ea-8345-0d93280f53d0.png)
The problem is the weird walls that kept on generating.

**Comment by zeyd6796** [comment]
Use the latest version, v0.0.9 please. This must have been fixed.
