### ISSUE TITLE
Problem with generation map

### ISSUE THREAD

**Issue by PB369** [TerraForged/TerraForged#91]
Description

During the configuration of the world generation, the map is not accurate in the area of ​​biomes and terrains. When the mouse cursor is passed in some places, **it is out of alignment with the biome and terrain presented.** The mod version is **0.0.9.**

![problem](https://user-images.githubusercontent.com/62622801/77476093-ac677600-6df8-11ea-9fa9-ece0f0e5477b.png)
**The red circle in image represent the mouse cursor when take screenshoot**

**Comment by dags-** [comment]
What do you mean out of alignment sorry?
Like you go to that location in-game and it's not that combination of terrain type and biome type?
