### ISSUE TITLE
Does this function server-side only?

### ISSUE THREAD

**Issue by B222006** [TerraForged/TerraForged#92]
I am wondering if I need to install this on both my client and server, or just my server.

**Comment by dags-** [comment]
Obviously it'd need to be a forge server, but yes you can do that with the following caveats:

1. Non-Forge clients will be able to connect fine, but if the client has Forge installed and not TerraForged, it will not be able to connect.

2. TerraForged's custom biomes will show up as the `minecraft:plains` biome so the grass and water colours will look out of place in some areas.

**Comment by import-antigravity** [comment]
> Obviously it'd need to be a forge server, but yes you can do that with the following caveats:
> 
> 1. Non-Forge clients will be able to connect fine, but if the client has Forge installed and not TerraForged, it will not be able to connect.
> 2. TerraForged's custom biomes will show up as the `minecraft:plains` biome so the grass and water colours will look out of place in some areas.

Would it be possible to generate the world with a forge client, then just use the world file on a non-forge server? Obviously you wouldn’t be able to generate new chunks but would the existing chunks work?
