### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by HolyRadiantPotato** [TerraForged/TerraForged#93]
Hi,

I can't build the project as stated in readme.
Unless the absence of the me folder is intended, and as such the readme is pointless

**Comment by dags-** [comment]
https://www.git-scm.com/docs/git-clone

**Comment by HolyRadiantPotato** [comment]
Maybe I misunderstood something, but this is my problem : 
![image](https://user-images.githubusercontent.com/62420939/77533823-dc198b00-6e97-11ea-9f46-58c570317c78.png)

**Comment by dags-** [comment]
I know. You need to use git to checkout the project
