### ISSUE TITLE
Dark Chunks

### ISSUE THREAD

**Issue by RogueGaming99** [TerraForged/TerraForged#94]
Areas that are not lit and mobs don't burn in.
![Inked2020-03-26_13 28 46_LI](https://user-images.githubusercontent.com/62723456/77695521-24ed4480-6f69-11ea-988c-c7fa255aade0.jpg)
![Inked2020-03-26_13 29 33_LI](https://user-images.githubusercontent.com/62723456/77695530-29b1f880-6f69-11ea-8f5e-90fc11c9a5b0.jpg)

**Comment by dags-** [comment]
1) Please can you check if the problem is repeatable (it happens in new TerraForged worlds) and let me knwo the steps to reproduce (including world seed, settings etc)

2) Please also check if this only happens on TerraForged world types, and not when using the vanilla generator
