### ISSUE TITLE
[1.15.2] Biome Finding Issue

### ISSUE THREAD

**Issue by Dragnier** [TerraForged/TerraForged#96]
**Description**
Having trouble finding Mountain and Mountain Edge biomes. Using Nature's Compass to search for them (it searches 10k block radius at a time). I've teleported around a few different random seed maps and had no luck finding either of these biomes at all. Basic Mountains shouldn't be all that rare...

**How to reproduce**
- Here is my current Twitch/Forge profile setup to import for testing:
[Bleeding Edge-1.0.0.zip](https://github.com/TerraForged/TerraForged/files/4392909/Bleeding.Edge-1.0.0.zip)

- Use the default TerraForged settings to create a world with a random seed. In Creative, grab a Nature's Compass and try to search for either the above biomes. Teleport around the map in 20k block intervals searching again each time.

**Comment by dags-** [comment]
TerraForged separates terrain from biomes - mountains are not considered a 'biome type' but a 'terrain type' that can sustain various different biomes.

The `minecraft:mountains` biome (and relatives) are not used

**Comment by Dragnier** [comment]
This is a bad decision because there are things which only spawn in certain biomes. Emerald ore for instance? Not to mention modded items/structures.

**Comment by dags-** [comment]
I'll look at adding emerald spawns elsewhere

**Comment by Dragnier** [comment]
You'll need to figure out some way to detect things from mods that only spawn in such biomes and have them placed accordingly too. For instance, Astral Sorcery has structures which only spawn in Mountains and some only in Deserts. Other mods have creatures which are biome spawn dependent... Not sure how that would work, though.

**Comment by Dragnier** [comment]
Even Thermal Expansion and other such mods have their ore gen set up per biome in the configs.

**Comment by Monsterfisch** [comment]
could reintroduce the mountain "biome" for the highest peaks of terrain, so starting around 20 blocks above the treeline for example.
