### ISSUE TITLE
[1.15.2] Incorrect Mesa/Plateau Generation

### ISSUE THREAD

**Issue by Dragnier** [TerraForged/TerraForged#97]
**Description**
Any biome that is supposed to have cliff-like generation such as Mesa or Plateau does not seem to actually generate as such. They tend to be just as flat as plains.

**How to reproduce**
- Here is my current Twitch/Forge profile setup:
[Bleeding Edge-1.0.0.zip](https://github.com/TerraForged/TerraForged/files/4392909/Bleeding.Edge-1.0.0.zip)

- Using TerraForged default settings, create a random seed world and then find biomes that are supposed to be Mesa or Plateau formations only to see that they are relatively flat.

**Comment by dags-** [comment]
Terrain and biomes are separate things in TerraForged.

The badlands biomes can decorate a much wider range of terrain types, so just because it looks one way in one area, it could be mountainous, hilly, plataued in others

**Comment by Dragnier** [comment]
Which would be fine if I ever saw any cliffs/plateaus. I think I saw maybe 5 or 6 such areas across a few hundred thousand blocks.
