### ISSUE TITLE
[1.15.2] Lack of any Trees in some Forest Biomes

### ISSUE THREAD

**Issue by Dragnier** [TerraForged/TerraForged#98]
**Description**
Biomes like Flower Forest and Forest have little or no trees at all.

**How to reproduce**
- Here is my current Twitch/Forge profile setup to import for testing:
[Bleeding Edge-1.0.0.zip](https://github.com/TerraForged/TerraForged/files/4392909/Bleeding.Edge-1.0.0.zip)

-Using TerraForged default settings, generate random seed worlds and check various forested biomes to find that many have no trees. Jungle, Dark Oak, and Birch forests seem fine most of the time but the more common forests are often devoid of any trees.

**Comment by dags-** [comment]
Forests adhere to a [treeline](https://en.wikipedia.org/wiki/Tree_line) so the higher you go, the less likely they'll spawn.

Flower forest currently inherits it's tree density from the plains biome where trees are sparse, which might be wrong.

**Comment by Dragnier** [comment]
Average world height in most of the randoms seed worlds I've made has been around 100+ pretty much everywhere instead of the normal 64. That could cause that I suppose... but that in itself sounds like a bug.

**Comment by dags-** [comment]
I've opened ticket #101 for the flower forest problem

**Comment by Dragnier** [comment]
That average 100+ world height was with the default configs by the way; I didn't change anything.
